### ISSUE TITLE
Minecraft crashing

### ISSUE THREAD

**Issue by TimmyTotten** [strikerrocker/VanillaTweaks#100]
**Describe the bug** (Required)
Minecraft is crashing due to this: java.lang.IllegalStateException: No renderer registered for vanillatweaks:entity_sit

**To Reproduce** (Required unless not known)
1. 

**Crash report (via. [Hastebin](http://hastebin.com/))**
https://hastebin.com/ujufelecuy.php

**Expected behavior** (Required)
i expected it to open normally

**Screenshots**
If applicable, add screenshots to help explain your problem. This may be skipped/removed.

**Versions:**(check log if you don't know)
 - Forge Version: 31.1.0
 - MC Version: 1.15.2
 - Mod Version: 1.15.2
 - JEI Version (if present) :
 - Baubles Version (if present) :
 - Curios Version (if present) :

**Additional context**
the whole error message: The game crashed whilst initializing game
Error: java.lang.IllegalStateException: No renderer registered for vanillatweaks:entity_sit

**Comment by strikerrocker** [comment]
This is due to optifine.
