### ISSUE TITLE
Add more precise targeting to the Homing enchantment

### ISSUE THREAD

**Issue by TheDirectorX** [strikerrocker/VanillaTweaks#106]
**Is your feature request related to a problem? Please describe.**
Arrows when enchanted Homing fly to the nearest target (you can kill with your back).

![2020-04-02_02 20 19](https://user-images.githubusercontent.com/43481085/78192816-5cd91800-7492-11ea-86c2-a8f998745b23.png)

**Describe the solution you'd like**
I would like that they hit the target in the direction of view.

Either rename the line: 
https://github.com/StrikerRockers-Mods/VanillaTweaks/blob/f3f6a8af986f09d62fab1693b56fe93bf2b23a72/src/main/resources/assets/vanillatweaks/lang/en_us.json#L41

On: `"enchantment.vanillatweaks.homing.desc": "Your arrows will be aimed at the nearest target.",`

**Comment by TheDirectorX** [comment]
Also, the `Spectral Arrow` doesn't work with this enchantment.

**Comment by strikerrocker** [comment]
#83 exists
