### ISSUE TITLE
Configuration files are created empty

### ISSUE THREAD

**Issue by TheDirectorX** [strikerrocker/VanillaTweaks#109]
**Describe the bug**
Configuration files are created in the **config** folder, but they are completely empty.

**To Reproduce**
1. Install mod with **Twitch Launcher**
2. Launch **Minecraft**

**Log output/error**
[debug.log](https://hastebin.com/aqakelapoh.md)

**Expected behavior**
I expected configuration files to be created with all values ( ͝סּ ͜ʖ͡סּ)

**Screenshots**
![image](https://user-images.githubusercontent.com/43481085/78395259-96cb2b00-7606-11ea-8700-7e9ea06d7f1b.png)

**Versions:**
 - Forge Version: `31.1.35` (tested on version `31.1.18` as well)
 - MC Version: `1.15.2`
 - Mod Version: `1.15.2.1.5.20` (also tested versions from `1.15.2.1.5.17` to `1.15.2.1.5.20`)

**Additional context**
Comment with a similar problem on [Curse #98](https://www.curseforge.com/minecraft/mc-mods/vanillatweaks?comment=98)

**Comment by 34638a** [comment]
@TheDirectorX The config files generate after a world is created. Try getting a new world generated.

**Comment by TheDirectorX** [comment]
**True**, but shouldn't this be generated during the loading of Minecraft? I'm not the only one who is confused.

**Comment by strikerrocker** [comment]
Hey just checked config by default are only generated after a world is loaded in mc 1.14 +. I currently generate the files alone that's why it's empty. I will change it so that files aren't generated by me but forge so it's consistent.

**Comment by strikerrocker** [comment]
Fixed in latest release.
