### ISSUE TITLE
VanillaTweaks enchantments appearing on items they don't belong on.

### ISSUE THREAD

**Issue by TeetoKaziim** [strikerrocker/VanillaTweaks#11]
Vanillatweaks: 1.1.14
Minecraft: 1.12.2
Forge: 14.23.1.2578
JEI: 4.8.5.138
Inventorytweaks: 1.63
Hwyla: 1.8.23-B38_1.12

When enchanting pants at an enchanting table, am getting Vigor, Nimble, and Hops, Homing, despite those only working on non-pants items.

When using "Dungeon Tactics", another mod, when witches would drop that mod's spell scrolls, they would sometimes have Vanillatweaks enchantments instead of the Dungeontactics ones, causing the game to crash when it would try to mouse-over the scroll.

In JEI, I am told I can anvil a Homing book onto 11 pages of vanilla items, when it's meant to just be a bow enchant.

Thanks a buncharoonie, and best of luck :D

**Comment by strikerrocker** [comment]
Fixed with the latest commit will push an update later
