### ISSUE TITLE
Blazing deletes non-smelting items

### ISSUE THREAD

**Issue by systemshaper** [strikerrocker/VanillaTweaks#110]
**Describe the bug** (Required)
When I apply blazing to a pick and mine a block that doesn't normally smelt, like granite, nothing drops at all.

**To Reproduce** (Required unless not known)
1. enchant a vanilla pick with blazing, mine any non-smelting block. nothing drops.

**Log output/error (via. [Hastebin](http://hastebin.com/))**
Get your minecraft log and paste it in the above link and paste the link here.

**Expected behavior** (Required)
Expect that blocks that can't smelt would simply drop themselves as normal.

**Screenshots**
If applicable, add screenshots to help explain your problem. This may be skipped/removed.

**Versions:**(check log if you don't know)
 - Forge Version: 28.2.3
 - MC Version: 1.14.4
 - Mod Version: 1.5.12
 - JEI Version (if present) :
 - Baubles Version (if present) :
 - Curios Version (if present) :

**Additional context**
Add any other context about the problem here. This may be skipped/removed.
Originally noticed the issue on a modded multiplayer server, and started a fresh single player world with all other mods removed where I was able to replicate.

**Comment by strikerrocker** [comment]
Fixed in latest release.
