### ISSUE TITLE
[1.14.4] Sapling auto plant rate

### ISSUE THREAD

**Issue by H4Mm3r** [strikerrocker/VanillaTweaks#111]
Sapling are auto planting at 99% rate, it's very difficult to break them. Any configuration to this ?

MC 1.14.4
Forge 28.2.3
VT 1.5.12

**Comment by strikerrocker** [comment]
Just checked it. Its working normally?

**Comment by strikerrocker** [comment]
Fixed in latest release.

**Comment by H4Mm3r** [comment]
Thanks !
