### ISSUE TITLE
[1.14.4] betterStairs settings disables the stairs recipes

### ISSUE THREAD

**Issue by H4Mm3r** [strikerrocker/VanillaTweaks#112]
Setting betterStairs to false disables concerned stairs recipes.

**To Reproduce** (Required unless not known)
1. Set to false
2. Try to craft Brick or Cobblestone stairs
3. Nothing happen

**Expected behavior** (Required)
4 stairs instead of 8

 - Forge Version: 28.2.3
 - MC Version: 1.14.4
 - Mod Version: 1.5.12
 - JEI Version (if present) :
 - Baubles Version (if present) :
 - Curios Version (if present) : 1.0.6.1

**Comment by strikerrocker** [comment]
Fixed in latest release

**Comment by H4Mm3r** [comment]
Wow nice job, thanks !
