### ISSUE TITLE
stone tool crarting config

### ISSUE THREAD

**Issue by EternalOne11** [strikerrocker/VanillaTweaks#114]
I would like it if you added a config option for the stone tool crafting improvements such as being able to use mossy cobblestone in the recipe.
**Module**
Crafting, Content, Enchanting, Loot, World, Tweaks. 
Crafting
**Is your feature request related to a problem? Please describe.**
Because there is no way to disable the stone tool crafting using mossy cobblestone est and this causes 2 sets of stone tools to appear in the recipe book when quarks stone tools are enabled.

**Describe the solution you'd like**
I would like a config to disable it.

**Describe alternatives you've considered**
Another solution is having the stone tool crafting recipe disabled when quark is installed.

**Additional context**
![2020-04-19_02 12 51](https://user-images.githubusercontent.com/42950385/79680950-590ffa00-81e3-11ea-82ef-7ce0be18bcda.png)
![2020-04-19_02 12 44](https://user-images.githubusercontent.com/42950385/79680952-5a412700-81e3-11ea-9b77-ea8ad4aa1895.png)
![2020-04-19_02 12 49](https://user-images.githubusercontent.com/42950385/79680954-5ad9bd80-81e3-11ea-92b4-e2c592cb8555.png)

**Comment by strikerrocker** [comment]
Hey from 1.13+ forge uses tags for recipes. So if you disable stone tools in recipe module of VanillaTweaks it automatically supports mossy cobblestone and such.

**Comment by EternalOne11** [comment]
I'm saying it is causing an issue with quark. which adds all that vanilla tweaks as well as having more. This is causing a visual bug in the recipe book where 2 recipes are appearing.

**Comment by EternalOne11** [comment]
thank you
