### ISSUE TITLE
Version 1.15.2.1.5.14 doesn't actually get rid of lava pockets in the nether.

### ISSUE THREAD

**Issue by XTO-Emperor** [strikerrocker/VanillaTweaks#115]
I was going to play with the mod, and was checking it out in specator mode, and there were still lava pockets everywhere in the nether

**To Reproduce** (Required unless not known)
1. Use the VanillaTweaks-1.15.2.1.5.14
2. Use spectator mode in the nether to see that lava pockets still generate.

**Log output/error (via. [Hastebin](http://hastebin.com/))**
Get your minecraft log and paste it in the above link and paste the link here.

**Expected behavior** (Required)
I expected for there to be no lava pockets in the nether because it says so in the wiki.

**Screenshots**
If applicable, add screenshots to help explain your problem. This may be skipped/removed.

**Versions:**(check log if you don't know)
 - Forge Version: 1.15.2 - 31.1.47
 - MC Version: 1.15.2
 - Mod Version: 1.5.14
 - JEI Version (if present) : 1.15.2 - 31.1.47
 - Baubles Version (if present) : X
 - Curios Version (if present) : X

**Additional context**
Add any other context about the problem here. This may be skipped/removed.
I used some other mods, that I don't think would interfere with nether generation (They had nothing to do with other dimensions, or physics), but it could have affected the mod's performance.

**Comment by strikerrocker** [comment]
Hey this feature isn’t available for 1.14+ version of mod.
