### ISSUE TITLE
Right-clicking signs will open the edit window even if 'enableSignEditing' is set to 'false'

### ISSUE THREAD

**Issue by JoakimYsland** [strikerrocker/VanillaTweaks#117]
**Describe the bug** (Required)
Right-clicking signs will open the edit window even if 'enableSignEditing' is set to 'false'. However, it will cause a 'Player just tried to change non-editable sign'-warning in the server console and it will not save any changes made to the sign. **However**, you can still edit signs that were placed during the same session. As soon as you reconnect, it will cause the warning as described above. 

**To Reproduce** (Required unless not known)
1. Change configuration to 'enableSignEditing = false'
2. Start the server
3. Enter the world and place a sign. **This sign will remain editable until you log out**
4. Disconnect and log back in
5. The sign will no longer save any changes made to it and it will cause a warning in the server console. 

This was reproduced on a new server with no other mods. 

**Log output/error
`[Server thread/WARN] [minecraft/MinecraftServer]: Player <playerName> just tried to change non-editable sign`

**Expected behavior** (Required)
A clear and concise description of what you expected to happen:

With 'enableSignEditing' set to 'false', I expect that right-clicking a sign will NOT bring up the sign editing window at all. 

**Versions:**(check log if you don't know)
 - Forge Version: 28.2.0
 - MC Version: 1.14.4
 - Mod Version: VanillaTweaks-1.14.4.1.5.12

**Comment by strikerrocker** [comment]
Fixed in 1.5.26 will release in a short while.
