### ISSUE TITLE
/give gives an extra item

### ISSUE THREAD

**Issue by Pannoniae** [strikerrocker/VanillaTweaks#119]
**Describe the bug** (Required)
When using /give, it gives me an extra item. (when giving 1 item I receive 2, when giving a stack it gives me 65)

**To Reproduce** (Required unless not known)
1. Create a world
2. Type /give <player> <itemname> <amount>
3. You receive amount+1 items

**Expected behavior** (Required)
Same behaviour as vanilla.
**Versions:**(check log if you don't know)
 - Forge Version: 31.1.88
 - MC Version: 1.15.2
 - Mod Version: 1.5.24
 - JEI Version (if present) : 6.0.0.4
 - Baubles Version (if present) : N/A
 - Curios Version (if present) : 2.0.2.2

**Comment by Pannoniae** [comment]
Did this get fixed? Or is it wontfix?

**Comment by strikerrocker** [comment]
Fixed in the latest version.

**Comment by Pannoniae** [comment]
Thank you!
