### ISSUE TITLE
Item don't despawn

### ISSUE THREAD

**Issue by bribri69** [strikerrocker/VanillaTweaks#120]
Throw items at floor and wait.
After few seconds they "jump" further... again... again and again... and they never despawn

Test with many differents items... always the same !

 - Forge Version: 31.2.0
 - MC Version: 1.15.2
 - Mod Version: 1.15.2.1.5.24
- No other mods

**Comment by bribri69** [comment]
Closed without explanation?

**Comment by strikerrocker** [comment]
Fixed in latest release

**Comment by bribri69** [comment]
Ok, thanks :)
