### ISSUE TITLE
Items despawn in less than a minute

### ISSUE THREAD

**Issue by bribri69** [strikerrocker/VanillaTweaks#121]
Throw items at floor and wait less than a minute and they despawn.

Test with many differents items... always the same !

    Forge Version: 31.2.0
    MC Version: 1.15.2
    Mod Version: 1.15.2.1.5.25
    No other mods

**Comment by strikerrocker** [comment]
I just tested this oh man i will look into it further later I guess.

**Comment by strikerrocker** [comment]
Fixed in 1.5.26 will release in a short while.

**Comment by bribri69** [comment]
Great !! 
Thank you for your reactivity !!
