### ISSUE TITLE
Items not used in crafting pad are deleted

### ISSUE THREAD

**Issue by Maytwa** [strikerrocker/VanillaTweaks#122]
**Describe the bug** (Required)
Any item not used up in recipe is lost when exiting crafting pad without removing items first.  They are not thrown down, or returned to inventory.

**To Reproduce** (Required unless not known)
1. add items to crafting pad, exit crafting, re-enter inventory to note items are gone.

**Log output/error (via. [Hastebin](http://hastebin.com/))**
not relavant...

**Expected behavior** (Required)
items should return to inventory

**Screenshots**
skipped

**Versions:**(check log if you don't know)
 - Forge Version:  14.23.5.2847
 - MC Version: 1.12.2
 - Mod Version: 1.12.2-1.5.6
 - JEI Version (if present) : 4.15.0.291
 - Baubles Version (if present) : 1.5.2
 - Curios Version (if present) :

**Additional context**
I am using modpack "life in the village" v 1.19 via twitch.

**Comment by strikerrocker** [comment]
1.12 version of the mod isn't supported anymore.
