### ISSUE TITLE
[1.16.1] Blazing + Fortune Enchantments combo is broken

### ISSUE THREAD

**Issue by Haddadmj** [strikerrocker/VanillaTweaks#127]
**Describe the bug** (Required)
When enchanting a tool with these enchantments ... when u break ore it doesn't smelt and apply fortune effect... it give you one ore

**Expected behavior** (Required)
It should melt the ores + applying the fortune

**Versions:**(check log if you don't know)
 - Forge Version: 32.0.70
 - MC Version:1.16.1
 - Mod Version: VanillaTweaks-1.16.1-1.5.29
 - JEI Version (if present) : 7.0.0.6
 - Baubles Version (if present) : Doesn't exsist
 - Curios Version (if present) : 1.16.1-3.0

**Additional context**
Add any other context about the problem here. This may be skipped/removed.
Tried blazing only enchantment pickaxe it melt ores
Tried blazing + fortunte only enchantment pickaxe it doesn't melt

**Comment by Chaest** [comment]
Same problem

**Comment by flodri** [comment]
same issue here, on 1.16.1, forge 0.98

**Comment by strikerrocker** [comment]
Only fortune or blazing can be applied at one time. If a tool has fortune and blazing, the tool will use fortune if not then it will use blazing there is no easy way to fix this other than stopping blazing and fortune being applied together. I will opt for later option.
