### ISSUE TITLE
[1.15.2] Crash with forge 31.2.31 at startup in multiplayer

### ISSUE THREAD

**Issue by porl** [strikerrocker/VanillaTweaks#128]
**Describe the bug** (Required)
When trying to run the latest (as of now) version of forge for Minecraft 1.15.2 (31.2.31) with this mod in multiplayer, the client fails to connect with the error:

`Internal Exception:io.netty.handler.codec.DecoderException: The received string length is longer than maximum allowed (137 > 128).`

**To Reproduce** (Required unless not known)
1. Set up a brand new forge 31.2.31 client and server for minecraft 1.15.2.
2. Add the VanillaTweaks mod and run
3. Try to connect
4. Client fails to connect to server with above error.

**Crash report (via. [Hastebin](http://hastebin.com/))**
No crash report as the client is technically still running but unable to connect.

**Expected behavior** (Required)
Client and server should successfully pass the handshake and connect.

**Versions:**(check log if you don't know)
 - Forge Version: 31.2.31
 - MC Version: 1.15.2
 - Mod Version: 1.15.2.1.5.28
 - JEI Version (if present) : N/A
 - Baubles Version (if present) : N/A
 - Curios Version (if present) : N/A

**Additional context**
Originally found this when updating forge and various mods in a custom modpack. Isolated to this mod. With other mods enabled sometimes the maximum allowed message length changes but same error occurs.

**Comment by strikerrocker** [comment]
Can you provide log?

**Comment by pau101** [comment]
It looks like the fix is using the wrong path for `createDirectories`, it needs the parent not the toml file.

**Comment by strikerrocker** [comment]
Thanks will fix it soon
