### ISSUE TITLE
I dont get how to acces the config menu

### ISSUE THREAD

**Issue by TimestaticYT** [strikerrocker/VanillaTweaks#129]
I am playing 1.16.1 forge and I don't know how to access the config menu. I looked in the Wiki or the official video but I see it nowhere mentioned so I just came here to ask how i get in the config menu

**Comment by strikerrocker** [comment]
The config screen is no longer present in 1.13+ forge. You can access the config by going to minecraft_directory/saves/world_name/serverconfig
