### ISSUE TITLE
Default vt.cfg is erroring on each launch

### ISSUE THREAD

**Issue by TeetoKaziim** [strikerrocker/VanillaTweaks#13]
Relevant Excerpt from fml-client-latest.log

https://pastebin.com/raw/mCFVMfcy

Suspicion: (I'm a scrub and don't know nothin, but, here's a wild guess:)
```
    miscellaneous {
        # Silence the sound of lightning
        B:=true
```
There maybe is meant to be a string between "B:" and "=true"?

In any case, thanks, again, for your time, and the best to you.

**Comment by strikerrocker** [comment]
Do mind deleting the old config and retrying

**Comment by TeetoKaziim** [comment]
Yeah, no problem, I can walk on through some of this:

So, starting from scratch, no config in the config folder, launch the game, it generates a vt.cfg in the config folder with the following:

https://pastebin.com/raw/Vz0fsu3S

Then, I close minecraft, and relaunch, having made no changes to vt.cfg, nor have I opened up the [Mods] menu to fuss with it there.

While launching, I get this in my config file:
https://i.imgur.com/5ppO0Ff.png
And my FML client latest log looks like this:
https://pastebin.com/raw/UrZsKTM6
(do a Control + F for "vt.cfg" to find the error mentioned in the initial post of this issue)

It dummies out the original config the mod generated with a .ERRORED file extension, then makes a new one. However, both files contain exactly the same text. On every relaunch, it'll do the same thing, over and over, forever.

Another thing I spotted that might be causing problems: In the config file the mod generates:
```
    drops {
        D:=4.0

        # Do baby zombies burn in daylight?
        B:"Baby zombies burn in daylight"=true
```
There probably should be a string between "D:" and "=4.0" maybe? I dunno.

Anyhow, I hope this information proved useful, and good luck. Thanks again.

**Comment by strikerrocker** [comment]
Can you please use the older versions an update is released. Thanks for taking your time to report this. 👍

**Comment by strikerrocker** [comment]
Are u on discord .I can send u custom jar if u want. I am available an Minecraft Mod Development Discord
