### ISSUE TITLE
Incompatibility with Vanilla Tweaks' Hops enchant while wearing the Cirrus / Nimbus Amulet from Botania

### ISSUE THREAD

**Issue by PokeMaserJ** [strikerrocker/VanillaTweaks#133]
**Describe the bug** (Required)

**To Reproduce** (Required unless not known)
1. Enchant a pair of Boots with Hops
2. Equip either amulet
3. notice you don't get the extra jump height from the enchant
**Log output/error (via. [Hastebin](http://hastebin.com/))**
Get your minecraft log and paste it in the above link and paste the link here.
n/a

**Expected behavior** (Required)
Expected to get the extra jump height from the Hops Enchant
**Screenshots**
If applicable, add screenshots to help explain your problem. This may be skipped/removed.

**Versions:**(check log if you don't know)
 - Forge Version: 34.1.23
 - MC Version: 1.16.3
 - Mod Version:
 - JEI Version (if present) : 1.16.3-7.6.0.49
 - Baubles Version (if present) :
 - Curios Version (if present) : curios-forge-1.16.3-4.0.2.0
Botania : 1.16.3-409
**Additional context**
Add any other context about the problem here. This may be skipped/removed.

https://github.com/Vazkii/Botania/issues/3495

**Comment by strikerrocker** [comment]
I have made an pull request which would fix this issue to the botania repository but it still hasn't been merged <https://github.com/VazkiiMods/Botania/pull/3790>

**Comment by strikerrocker** [comment]
Issue fixed in botania side.
