### ISSUE TITLE
Blazing enchantment not working correctly.

### ISSUE THREAD

**Issue by im-hyps** [strikerrocker/VanillaTweaks#134]
**Describe the bug** 
I have a pickaxe enchanted with Blazing, Fortune III, Siphon & Magnetic. When mining anything, it does not smelt it (even Cobblestone).

**To Reproduce**
1. Enchant a pickaxe with Fortune, Siphon & Blazing.
2. Mine any smeltable block.

**Expected behavior**
Acquiring multiple ingots from ores, and regular stone from stone instead of cobble.

**Screenshots**
https://i.imgur.com/7T55MbD.png

**Versions:**(check log if you don't know)
 - Forge Version: 32.2.45
 - MC Version: 1.15.2
 - Mod Version: 2.1.5.30
 - JEI Version (if present) : 6.0.3.15
 - Baubles Version (if present) : 1.7.12
 - Curios Version (if present) : 2.0.2.6

**Comment by im-hyps** [comment]
Further testing shows that adding Fortune completely cancels Blazing, no matter the order or other enchantments.

**Comment by strikerrocker** [comment]
Blazing isn't compatible with fortune.
