### ISSUE TITLE
Tooltip for a spawner causes client to crash

### ISSUE THREAD

**Issue by GSValore** [strikerrocker/VanillaTweaks#135]
**Describe the bug** (Required)
Client crashes when hovering over a spawner in the player inventory.  It may be specific to wolf spawners.

**To Reproduce** (Required unless not known)
1. Silk touch a spawner and place it.
2. Apply an egg to it for type change -- in this case, wolf.
3. Pick up the spawner again and hover over it in your bags; client crashes.

**Crash report (via. [Hastebin](http://hastebin.com/))**
[Crash report](https://hastebin.com/gisaquxicu.rb)

**Expected behavior** (Required)
Expected is the tooltip for the item would appear normally and no crash occur.

**Versions:**(check log if you don't know)
 - Forge Version: 34.1.42
 - MC Version: 1.16.3
 - Mod Version: 1.5.34
 - JEI Version (if present) : 7.6.0.51
 - Baubles Version (if present) : N/A
 - Curios Version (if present) : 4.0.2.0

**Comment by IchigoGames** [comment]
same crash happend on my pack and it was not a wolf spawner also was 1.16.4

**Comment by IchigoGames** [comment]
https://pastebin.com/HNjmT5Cv

**Comment by strikerrocker** [comment]
Was the mob renamed by any chance?

**Comment by GSValore** [comment]
As far as I know, the mob was not renamed in our case.

**Comment by IchigoGames** [comment]
i forgot this was a issue but it just happend with me when i try to hover over a enderman spawner i picked up using silk pick https://pastebin.com/HMNs2nVp

**Comment by strikerrocker** [comment]
Hey may i ask where was the spawner item location in the inventory? A backpack?

**Comment by strikerrocker** [comment]
Also can ya join my discord i will give ya a test version in #minecraft-mods channel with a fix but i am not it will work or work.
https://discord.gg/tqcqeSj

**Comment by IchigoGames** [comment]
it was in main inv not bacpack

**Comment by IchigoGames** [comment]
for now i turned of picking up spawner with vannila tweeks and turned on picking up spawner with  Apotheosis could be a mod conflict but that stoped the crashing

**Comment by strikerrocker** [comment]
I have a test version in my discord can ya try it and check whether it doesnt crash?

**Comment by IchigoGames** [comment]
sure one min

**Comment by IchigoGames** [comment]
that worked it no longer says what kind of spawner it is but it did stop crashing

**Comment by strikerrocker** [comment]
ok will release an official version thanks
