### ISSUE TITLE
Zombies aren't vampires.

### ISSUE THREAD

**Issue by K0-RR** [strikerrocker/VanillaTweaks#136]
You added creepers burning in daylight. There is one more thing in need to be happy...

Why do zombies burn in daylight? I don't know too. This is the only game where zombies won't like sun. Why aren't they called vampires then?
Please let zombies live in daylight.

**Comment by strikerrocker** [comment]
> This is the only game where zombies won't like sun. Why aren't they called vampires then?
Ask Mojang
This seems like a not vanilla esque feature so i won't be adding it to the mod.

**Comment by K0-RR** [comment]
How is making creepers burn in daylight ok but doing the opposite with zombies not? I don't want to be rude but it just doesn't make sense to me. Anyway I have other suggestions. Do you prefer one issue per idea or it would be better to list them in one issue?

**Comment by strikerrocker** [comment]
Hey compared to zombie's creepers spawn less times in the game and the world damage/exploding blocks also happens so i decided to have the creepers burn in daylight but zombie's spawn a lot more and not burning them in daylight would cause people to look out all time of the day and in vanilla it's supposed to be only at night thus I dont want to change it.

 Also it isn't rude voicing your opinion.

For other ideas i would recommend joining my server and discussing it with me before creating an issue. 😀
Discord invite : https://discord.gg/tqcqeSj
