### ISSUE TITLE
Dynamite Config

### ISSUE THREAD

**Issue by Duxtorm** [strikerrocker/VanillaTweaks#137]
**Type**
Dynamite

**Module**
Configuration

**Is your feature request related to a problem? Please describe.**
I'm almost certain that there used to be a way to customise the dynamites stack size and cooldown as I remember doing it a while ago.. though it's possible that I somehow did it through editing the .jar file directly, I don't remember.

**Describe the solution you'd like**
Seeing as these config options are gone or never existed in the first place, I would totally love the config file to include max stack size and cooldown time or toggle for the dynamite.

I super duper love your mod!

**Comment by strikerrocker** [comment]
Hey i unfortunately can't add an config for stack size but an configuration for cooldown and explosion power is added.

**Comment by Duxtorm** [comment]
> 
> 
> Hey i unfortunately can't add an config for stack size but an configuration for cooldown and explosion power is added.

♥
