### ISSUE TITLE
Crash on startup with version 1.5.38

### ISSUE THREAD

**Issue by remplerus** [strikerrocker/VanillaTweaks#138]
**Describe the bug** (Required)
Starting Minecraft with updated VT version 1.5.38 installed crashes on startup

**To Reproduce** (Required unless not known)
1. install VT 1.5.38

**Crash report (via. [Hastebin](http://hastebin.com/))**
https://gist.github.com/remplerus/206f8e9751c8f0a36ff43bbb62332ef7

**Expected behavior** (Required)
Starting of client like it should

**Versions:**(check log if you don't know)
 - Forge Version: 35.1.37
 - MC Version: 1.16.4
 - Mod Version: 1.5.38
 - JEI Version (if present) : 7.6.0.62

**Comment by strikerrocker** [comment]
version 1.5.39 fixes the crash.
