### ISSUE TITLE
Configuration File Ignored

### ISSUE THREAD

**Issue by Dude20121** [strikerrocker/VanillaTweaks#139]
**A clear and concise description of what the bug is:**
Despite disabling items in the config provided, they still appear in-game. I'm assuming other tweaks don't change either.

**Steps to reproduce the behavior:**
1. Try to disable an item added by the mod
2. Look for item in creative inventory or JEI menu

**A clear and concise description of what you expected to happen:**
Expected the mod to use the configuration changes that I made.

**Versions:**
 - Forge Version: 36.1.4
 - MC Version: 1.16.5
 - Mod Version: 1.5.39
 - JEI Version: 7.6.4.86
 - Curios Version: 4.0.5.0

**Comment by strikerrocker** [comment]
The items are disabled, the recipes for items will be disabled when
disabled in config.

**Comment by Dude20121** [comment]
Thanks for the quick reply, I should've looked a little closer.
