### ISSUE TITLE
Creepers not burning when enabled

### ISSUE THREAD

**Issue by jprocket45** [strikerrocker/VanillaTweaks#14]
I have tried with other mods at first but decided to give it a try with just this mod by itself creepers burn daylight enabled it does not allow them to burn, or maybe its just me :P

# Do creepers burn in daylight?
        B:"Creepers burn in daylight"=true

**Comment by strikerrocker** [comment]
Do baby zombie burn?

**Comment by strikerrocker** [comment]
Currently at holidays so cant check it out myself

**Comment by jprocket45** [comment]
yes baby zombies burn with no issues.

**Comment by strikerrocker** [comment]
Not sure whats the cause :thinking:

**Comment by jprocket45** [comment]
me neither but can't seem to get them to burn lol enjoy ur holiday maybe you can look at it more when you get back!!

**Comment by strikerrocker** [comment]
Thanks for nice words will look at it soon

**Comment by jprocket45** [comment]
just a correction baby zombies don't burn either I tried it was just vanilla tweaks installed no burn ... when i tested it i realized i had quark installed with allows baby zombies to burn as well.

**Comment by strikerrocker** [comment]
I think i have found the cause of the issue. Will release an update when i am back from holidays 

**Fix:**
used`getBrightness(1)` instead of `getBrightness`

**Comment by jprocket45** [comment]
sounds good can't wait for the update!! hopefully in the next couple days!!
