### ISSUE TITLE
[1.16.5] Block Duping issues when Siphon enchantment is applied to specific Upgraded Netherite tools.

### ISSUE THREAD

**Issue by Gbergz** [strikerrocker/VanillaTweaks#140]
**Describe the bug**
When all the Golderite, Corrupterite & Ultimerite tools/weapons from the mod [Upgraded Netherite](https://www.curseforge.com/minecraft/mc-mods/upgraded-netherite) are enchanted with the Siphon enchantment from VanillaTweaks any blocks mined will be duplicated, this means Shulker Boxes with loads of stuff inside them can easy be duplicated. Along with all other blocks.

The issue can easily be replicated by having just Upgraded Netherite & VanillaTweaks in a clean instance.

**To Reproduce**
1. Install [Upgraded Netherite](https://www.curseforge.com/minecraft/mc-mods/upgraded-netherite) & VanillaTweaks (only those.)
2. Go creative & grab a Golderite, Corrupterite or Ultimerite pickaxe for example.
3. Enchant it with the enchantment "Siphon".
4. Go back to survival mode. Mine any block.
5. Mined blocks will be duplicated.

**Expected behavior**
- That the mined blocks don't get duplicated.

**Video of the issue:**
https://streamable.com/d14d40

**Versions:**
- Minecraft: 1.16.5
- Forge: 36.1.31
 - VanillaTweaks Version: [1.5.39](https://www.curseforge.com/minecraft/mc-mods/vanillatweaks/files/3175153)
 - Upgraded Netherite Version: [1.9.5](https://www.curseforge.com/minecraft/mc-mods/upgraded-netherite/files/3331839)
 - JEI Version: 7.7.0.106
 - Curios Version: 4.0.5.2

**Additional context**
I've reported this issue first on the Upgraded Netherite issue tracker, which then lead me here.
https://www.curseforge.com/minecraft/mc-mods/upgraded-netherite/issues/24

Hopefully this can get fixed.
Thanks,
**-** Gbergz

**Comment by Gbergz** [comment]
🤔

**Comment by strikerrocker** [comment]
I can't really fix this issue if i can't see the source for that mod i forgot to comment.
