### ISSUE TITLE
[Bug] All Advancements from mod on start

### ISSUE THREAD

**Issue by KrolMC** [strikerrocker/VanillaTweaks#141]
**Describe the bug**
When I loaded world with VanillaTweaks I on start got all advancements from mod.

**To Reproduce** (Required unless not known)
1.  Create new world with VanillaTweaks Mod
2.  See chat or advancements GUI.

**Log output/error (via. [Hastebin](http://hastebin.com/))**
[latest.log](https://github.com/StrikerRockers-Mods/VanillaTweaks/files/6882779/latest.log)

**Screenshots**
![image](https://user-images.githubusercontent.com/64356973/127098105-ee1c12b8-8098-4018-8a58-56cee4390819.png)

**Versions:**
 - Forge Version: 37.0.12
 - MC Version: 1.17.1
 - Mod Version: 1.5.40

**Comment by strikerrocker** [comment]
This is an forge bug which causes all the not vanilla advancements to be given on world load. There is already a bug report for it in forge repository.
