### ISSUE TITLE
[1.16] Hops enchantment cancels/reduces the momentum of the player when jumping

### ISSUE THREAD

**Issue by Duxtorm** [strikerrocker/VanillaTweaks#146]
Uh... hello, me again x-x; (I'm sorry)

I've spent a good portion of 3 hours doing experiments back and forth between the effects of the **Hops Enchantment** and the **Jump Boost effect**.. eventually I was able to create a scenario which clearly demonstrated the difference between the two.

If I give myself **speed effect 12** ( XII + I ), I'm able to make a 7-block jump easily enough. 
If I then give myself **jump boost 0** ( I ) on top of the **speed effect**, I'm able to make the jump easier.. each time I increase the level of the **jump boost effect**, the jump gets easier and I'm able to make it further and further across, however-
If I instead use boots with the **Hops enchant 1-3** (still with speed 12), it hinders my ability to make the jump, often losing all my momentum and falling to the ground only 4-5 blocks from where I jumped.

Immediately after my first time trying hops + nimble, I found that every time I jumped, my momentum would deplete immediately. 
Continuously jumping would make me travel at a normal, unaffected pace as I jumped, regardless of any speed buff.

Jump boost on the other hand, preserves much of your momentum, giving you smoother, more effective jumps.

From all this, my only conclusion is, I feel the Hops enchantment would be much more appealing if it didn't halt your momentum when you jump, and I feel that it actually hinders your over-all ability to travel.

 - Forge Version: 36.2.4
 - MC Version: 1.16.5
 - Mod Version: 1.5.42
 - JEI Version (if present) : 7.7.1.121
 - Baubles Version (if present) : n/a
 - Curios Version (if present) : n/a
 
Side note: (Unrelated and unimportant)
I've also found that there is absolutely no difference between the effects of the Nimble enchant and the Speed effect XD

[Sprinting]

None       - 100 Blocks | 17.80 Sec (≈ 5.62 Blx/s)

Nimble I   - 100 Blocks | 14.80 Sec (≈ 6.75 Blx/s)
Nimble II  - 100 Blocks | 12.70 Sec (≈ 7.87 Blx/s)
Nimble III - 100 Blocks | 11.20 Sec (≈ 8.93 Blx/s)

Speed I    - 100 Blocks | 14.80 Sec (≈ 6.75 Blx/s)
Speed II   - 100 Blocks | 12.70 Sec (≈ 7.87 Blx/s)
Speed III  - 100 Blocks | 11.20 Sec (≈ 8.93 Blx/s)

--

[Jump Height]

None              - 1.25

Hops I             - 2.250 Blocks
Hops II            - 2.875 Blocks
Hops III           - 3.625 Blocks

Jump Boost I   - 1.750 Blocks
Jump Boost II  - 2.500 Blocks
Jump Boost III - 3.250 Blocks

**Comment by strikerrocker** [comment]
lHops is implement such that it adds jump boost whereas nimble uses the entity attributes. Maybe thats causing the issue?

I am not sure i understand the problem fully Can you contact me via discord for further contact and some clarification.

**Comment by Duxtorm** [comment]
Sure! Though, how do I find your Discord?
Mine's Mishka#6236

**Comment by strikerrocker** [comment]
https://discord.gg/tqcqeSj

**Comment by strikerrocker** [comment]
Fixed the issue and uploaded an new version on curseforge.
