### ISSUE TITLE
Blazing enchantment not dropping smeltable things

### ISSUE THREAD

**Issue by BuilderDan** [strikerrocker/VanillaTweaks#15]
Can't comment on the actual curse area, so I wanted to ask whether having items disappear when broken with blazing was a feature? Since at the moment if you break anything else that isn't smeltable with blazing, it just disappears, nothing drops... doesn't seem like a feature.

**Comment by strikerrocker** [comment]
It isnt a intended things. Tahnks for reporting thing will push a bug fix
later

**Comment by BuilderDan** [comment]
Thanks!
