### ISSUE TITLE
Siphon = Blaze 1.17

### ISSUE THREAD

**Issue by Halibear** [strikerrocker/VanillaTweaks#150]
**Describe the bug** (Required)
I'm putting Siphon on a diamond pickaxe and it blazes instead of siphons

**To Reproduce** (Required unless not known)
1. Create new world in survival, switch gamemode to creative
2. Grab Diamond Pickaxe, Siphon, and Anvil
3. Place anvil, add Diamond Pickaxe & Siphon, grab output item
4. Switch gamemode back to survival
5. Mine stone, Output = stone dropped on ground (no Siphon effect) instead of cobble stone

**Expected behavior** (Required)
Expected Siphon effect with cobble stone

**Versions:**(check log if you don't know)
 - Forge Version: 37.0.103
 - MC Version: 1.17.1
 - Mod Version: 1.5.48
 - JEI Version (if present) : removed for description of steps above but normally using: 8.1.0.26
 - Baubles Version (if present) : nope
 - Curios Version (if present) : nope

**Additional context**
Can reproduce with no other mods present on new world.

**Comment by strikerrocker** [comment]
For several minutes i was like how the heck this happens and after looking at the code i realize i messed up. 🤦 Fixing currently
