### ISSUE TITLE
Veteran can be put on Enchanted Wolves collars

### ISSUE THREAD

**Issue by Mikzoru** [strikerrocker/VanillaTweaks#151]
I'm not sure whether or not it is within your ability to fix this or if it is an issue on Enchanted Wolves's side, but I suppose it might be worth a try to let both mod devs know anyway.
Anyway, the issue is that the "Veteran" enchantment is able to be put on wolf collars from the Enchanted Wolves mod, but it does not do anything. I don't think it is supposed to do anything for wolves anyway, as they cannot absorb or attract experience orbs by default, and for this reason Mending is unable to be put on collars.

1. Put any collar from Enchanted Wolves in an enchantment table. There will be a chance that it will be enchanted with Veteran as a result.
2. Alternatively, you can use a Veteran enchanted book on a collar in an anvil.

**Expected behavior**
Collars should be unable to be enchanted with Veteran.

**Versions:**(check log if you don't know)
 - Forge Version: 36.2.4
 - MC Version: 1.16.5
 - Mod Version: VanillaTweaks 1.5.46 and Enchanted Wolves 1.1.0.1
 - JEI Version: 7.7.1.136
 - Curios Version: 4.0.5.3

**Comment by strikerrocker** [comment]
This has to be fixed on enchanted wolves side.
