### ISSUE TITLE
[1.18-Forge] Potion Effect shown in the inventory is in the middle of the inventory when this mod is installed.

### ISSUE THREAD

**Issue by Gbergz** [strikerrocker/VanillaTweaks#152]
**Describe the bug**
Potion Effect shown in the inventory is in the middle of the inventory when this mod is installed.

**To Reproduce**
1. Install VanillaTweaks
2. Apply any potion effect.
3. Open inventory.
4. Effect is now in the middle of the inventory screen.
5. Profit.

**Expected behavior**
That the potion effect is on the right side (like it was changed to be in 1.18).

**Screenshots**
![image](https://user-images.githubusercontent.com/26634554/144605081-c0b768d5-8d96-4282-9eb9-cde11fa3a7d5.png)

**Versions:**(check log if you don't know)
 - Forge Version: 38.0.12
 - MC Version: 1.18
 - Mod Version:1.18-1.5.51
 
 **-** Gbergz

**Comment by strikerrocker** [comment]
Seems to be an forge issue I would recommend turning of disablePotionShift config option until forge fixes this.

**Comment by Gbergz** [comment]
Ah gotcha, well disabling that solved it. Thanks.

**Comment by strikerrocker** [comment]
This feature is now removed from the mod.
