### ISSUE TITLE
[1.18-forge] Lava pockets being generated in Nether when Option to remove them is turned on.

### ISSUE THREAD

**Issue by ffuentesm** [strikerrocker/VanillaTweaks#153]
**Describe the bug** (Required)

**To Reproduce** (Required unless not known)
1. set the option to remove lava pockets on.
2. go to nether and you will find the 1 block lava pockets

**Log output/error (via. [Hastebin](http://hastebin.com/))**
Get your Minecraft log and paste it in the above link and paste the link here.

**Expected behavior** (Required)
there should have been no lava pockets

**Screenshots**
If applicable, add screenshots to help explain your problem. This may be skipped/removed.
![image](https://user-images.githubusercontent.com/44974827/145545571-0edbd981-9bfa-406d-813f-4dacd6ca9a73.png)

**Versions:**(check log if you don't know)
 - Forge Version:  38.016
 - MC Version: 1.18
 - Mod Version: VanillaTweaks-1.18-1.5.51.jar
 - JEI Version (if present) : jei-1.18-9.0.0.40.jar
 - Baubles Version (if present) :
 - Curios Version (if present) : curios-forge-1.18-5.0.2.4.jar

**Additional context**
Add any other context about the problem here. This may be skipped/removed.

**Comment by strikerrocker** [comment]
I can't reproduce this issue. The lava will be removed in the newly generated chunks after only a game restart.

**Comment by strikerrocker** [comment]
I might have made an possible fix for this issue try the latest version 1.5.52.

**Comment by ffuentesm** [comment]
Sorry, but version VanillaTweaks-forge-1.18.1-1.5.53.jar re introduced this problem

**Comment by strikerrocker** [comment]
The lava pockets wouldn't be removed from old chunk only prevents new chunk from generating with lava pockets.

**Comment by ffuentesm** [comment]
I know, and this is a new game.

**Comment by strikerrocker** [comment]
Can you join my discord : https://discord.gg/tqcqeSj

**Comment by strikerrocker** [comment]
Also screenshots of the lava pocket and the seed location will  be appreciated
