### ISSUE TITLE
Could you please add an configurable timing to the replanter in 1.18.1?

### ISSUE THREAD

**Issue by TheButterbrotMan** [strikerrocker/VanillaTweaks#158]
Would be useful, because for me personally 3 seconds is much to short.

**Comment by strikerrocker** [comment]
What modloader are you requesting for forge or fabric?

**Comment by strikerrocker** [comment]
Never mind I understand its for fabric I am currently looking into making a better implementation of this feature. Currently both loaders have different implementation and I don't like both the implementations so I am looking for a better one.

**Comment by TheButterbrotMan** [comment]
Yes, exactly. I talking of the .fabric version.

**Comment by jarocajavi** [comment]
+200

**Comment by strikerrocker** [comment]
Added the config option
