### ISSUE TITLE
[1.18.2] Forge 40.0.18 breaks mod

### ISSUE THREAD

**Issue by Baggytrousers27** [strikerrocker/VanillaTweaks#163]
Vanilla Tweaks (vanillatweaks) has failed to load correctly
java.lang.reflect.InvocationTargetException: null

VanillaTweaks-forge-1.18.2-1.5.54Forge 40.0.18

[Crashlog](https://pastebin.com/0TJa9rPw)

**Comment by strikerrocker** [comment]
Fixed thanks for the report 😄

**Comment by Baggytrousers27** [comment]
All groovy. ¦D
