### ISSUE TITLE
[Crash] - Exception ticking world - Dynamite throw crashes server for ever

### ISSUE THREAD

**Issue by xR4YM0ND** [strikerrocker/VanillaTweaks#167]
I disabled Dynamite in the config but it still shows up when entering the server. 

I get it -> i throw it -> Server crashes -> i wanna rejoin -> server crashes again & again ( i cant rejoin cause Exception ticking world )

1.Crash = [latest.log](https://gist.github.com/SpigotDE/6e8da929d9dd8b265093a22968bf9d67)
1.Crash = [crash report](https://gist.github.com/SpigotDE/2a08a3d0a86edcc394e32508fe32c6f9)

2.Rejoin [latest.log](https://gist.github.com/SpigotDE/d7adafc55cbba2c273e6ff539539bbe6)
2.Rejoin [crash report](https://gist.github.com/SpigotDE/e30f6ab7e4045ce8d932cb23cb8c8085)

So now i cant rejoin the world cause of the dynamite throw (that i disabled in config btw) 

The only way i can rejoin is to delete VanillaTweaks -> join ones -> add VanillaTweaks. 
But thats not a permanent solution, all the data gets gone in this process... 

BTW Im using "Flan Mod" for claiming Land and for protecting blocks

**Comment by strikerrocker** [comment]
Fixed in latest build thanks for reporting :)

**Comment by xR4YM0ND** [comment]
Thx for fixing <3
