### ISSUE TITLE
[1.18.2] self planting crashes the game when joining a world

### ISSUE THREAD

**Issue by ffuentesm** [strikerrocker/VanillaTweaks#168]
When I join the world I get this crash message

> -- Entity being ticked --
> Details:
>     Entity Type: minecraft:item (net.minecraft.world.entity.item.ItemEntity)
>     Entity ID: 45
>     Entity Name: Potato

> io.github.strikerrocker.vt.world.SelfPlanting.plant(SelfPlanting.java:94) ~[VanillaTweaks

![image](https://user-images.githubusercontent.com/44974827/165188608-55d4e1fe-9854-4c70-a862-4fbe666a3f37.png)

![image](https://user-images.githubusercontent.com/44974827/165188468-39137d80-1ef4-4b5c-a2a4-00abc8589bdb.png)
VanillaTweaks-forge-1.18.2-1.5.57.jar

https://crashy.net/jwl0rY0whxqiND1H2Qj2

**Comment by Reshy** [comment]
Having the same issue:
https://pastebin.com/qvpZiPYT

**Comment by strikerrocker** [comment]
Caused by MinecraftForge/MinecraftForge#8602 For now I would recommend disabling self planting in config to not crash.

**Comment by strikerrocker** [comment]
Using forge version 40.1.18 should fix this issue.
