### ISSUE TITLE
Tweaks not working

### ISSUE THREAD

**Issue by Modeeves** [strikerrocker/VanillaTweaks#170]
Hi there! I'm using your mod on 1.19 (VanillaTweaks-forge-1.19-1.5.59). Here is the list of which are not working among the tweaks you made:

1. When I right-click to replant and harvest (I have my seeds with me).
2. Falling tree.
3. Sit on slabs and stairs by right-clicking with an empty hand.
4. The placed signs cannot be edited (I right-clicked it with an empty hand) and the shift-right-click to clear the sign isn't working as well.
5. Mob Spawners don't drop themselves when you use silk touch.
6. Shift-right-click an armor stand to swap isn't working.
7. Hoe doesn't act as a sickle.

Thank you!!!

**Comment by strikerrocker** [comment]
Sorry for late reply been busy.
1. Right click to replant and harvest isn't available in VanillaTweaks.
2. Falling tree also not available.
3. Sit on slabs and stairs is a features I have removed from VanillaTweaks some while ago. ( Use [Sit mod](https://www.curseforge.com/minecraft/mc-mods/sit) )
4. You need to shift right click to edit signs.
5. I just tested and it seems to work. Make sure you have the config for the feature is enabled on config. If you can still reproduce create a new issue with exact reproduction step, mods  and possibly video of it.
6. Same as point 5.
7. Same as point 5.

You can find the updated list of features [here](https://strikerrocker.github.io/vanillatweaks/)
