### ISSUE TITLE
Silk Touching Spawners Error - version 1.18.2-1.5.57

### ISSUE THREAD

**Issue by WordStormRose** [strikerrocker/VanillaTweaks#172]
In the version of VanillaTweaks I use in my modpack Lennbain (VanillaTweaks version 1.18.2-1.5.57), silk touching spawners works properly in singleplayer/LAN (a zombie spawner, when picked up with silk touch can be placed back down again still as a zombie spawner) but on the server all the spawners become just pig spawners when placed back down.

**Comment by strikerrocker** [comment]
Sorry for the late response but I can't seem to reproduce the issue in both LAN and server. Can you try using the latest version?
