### ISSUE TITLE
Hops and Nimble lvl have no effect

### ISSUE THREAD

**Issue by TheCherry** [strikerrocker/VanillaTweaks#173]
For Hops and Nimble the level have no effect. All 3 level adds the same moving speed and jump height.
Version: 1.5.60
MC: 1.19

**Comment by strikerrocker** [comment]
I can't reproduce this issue with only VanillaTweaks. Can you try with VanillaTweaks alone and try narrowing down the mod which causes the issue? Also which mod loader?

**Comment by strikerrocker** [comment]
Closing the issue as no reply.
