### ISSUE TITLE
Config not working - Minecraft 1.19.1 - Forge

### ISSUE THREAD

**Issue by DreamDevourer97** [strikerrocker/VanillaTweaks#175]
Not sure if it's a problem with Forge or with the mod, but the "Config" button does not allow me to configure the mod.
If I am simply missing something, please advise.
Mod version 1.5.61

**Comment by strikerrocker** [comment]
Hey sorry for the late reply. Essentially the config button doesn't work in forge. Its been planned to implement it in forge. You can edit the config in minecraft_dir/config/vanillatweaks.toml
