### ISSUE TITLE
Creative inventory and JEI

### ISSUE THREAD

**Issue by Dinocraft1515YT** [strikerrocker/VanillaTweaks#183]
**Describe the bug**
The items of this mod don't appear in the creative inventory and JEI

**To Reproduce**
I don't know how it happen

**Video**
https://clipchamp.com/watch/Gu6ILKJGxtm

**Versions (please complete the following information):**
 - Fabric Loader Version: 0.4.11
 - MC Version: 1.19.2
 - Mod Version: 1.5.63
 - JEI Version (if present) : 11.4.0.287
 - Fabric API Version (if present) : 0.68.0

**Comment by Dinocraft1515YT** [comment]
Actually, this happens since I used "Minecraft Mod Uptader" https://www.curseforge.com/minecraft/mc-mods/minecraft-mod-updater

**Comment by strikerrocker** [comment]
Not supporting tlauncher...

**Comment by Dinocraft1515YT** [comment]
> Not supporting tlauncher...

Why? Because it's non-premium? In case we non-premium don't have rights?

**Comment by strikerrocker** [comment]
Not supporting people who don't buy the game.
