### ISSUE TITLE
[Crash] crash on startup after update mod(1.5.64->1.5.65)

### ISSUE THREAD

**Issue by MilkissWhite** [strikerrocker/VanillaTweaks#184]
**Describe the bug**
Game client crash after few seconds I pushed "PLAY" in Minecraft Launcher

**Crash report (via. [Hastebin](http://hastebin.com/))**
https://hastebin.com/share/kojoresole.css

**To Reproduce**
1. Start Minecraft
2. See error

**Versions:**(check log if you don't know)
 - Forge/Fabric Loader Version: Fabric - 0.14.17
 - MC Version: 1.19.3
 - Mod Version: 1.5.65
 - JEI Version (if present) : 12.3.0.21(test without JEI also same result)
 - Fabric API Version (if present) : 0.75.1

**Additional context**
I using CurseForge app for manage mods.

- test case 01 : VanillaTweaks 1.5.64 + play with many mods.
--result : work normally.
- test case 02 : update VanillaTweaks to 1.5.65 + play with many mods.
--result : crash on startup
- test case 03 : downgrade VanillaTweaks to 1.5.64 + play with many mods.
--result : work normally.
- test case 04 : Create new setting with Fabric Loader / Fabric API / MineCraft version same. newly install VanillaTweaks 1.5.65 and requirements(Cloth Config API 9.0.94) + play with just VT and requirement only.
--result : crash on startup(pasted link above is Crash report of this case).
- test case 05 : downgrade VanillaTweaks to 1.5.64 + play with just VT and requirement only.
--result : work normally

**Comment by strikerrocker** [comment]
Fixed thanks for the creating the issue.

**Comment by MilkissWhite** [comment]
after 1.5.66 update, also crash on startup. same condition as test case 04 except VanillaTweaks 1.5.66.
here is report.
https://hastebin.com/share/ucovurohag.css

**Comment by strikerrocker** [comment]
Seems to be an issue when building with Github actions will look into it further for now use 1.5.64 of the mod.

**Comment by strikerrocker** [comment]
Released a version manually to both curseforge and modrinth with same version no.
