### ISSUE TITLE
[BUG] : No enchantments in JEI

### ISSUE THREAD

**Issue by Telezhka-the-First** [strikerrocker/VanillaTweaks#186]
**Describe the bug**
Enchantments from this mod don't show uses in JEI tabs.

**To Reproduce**
1. Get a pickaxe (for example).
2. Notice that «Blazing» enchantment is applicable to it.
3. Check uses for the pickaxe or mentioned enchantment.
4. Observe the absence of modded enchantments in tabs.

**Expected behavior**
Observe enchantments from this mod in the tab (showed in pictures).

**Screenshots**
![2023-03-24_04 24 40](https://user-images.githubusercontent.com/90337398/227400746-b84362ba-ee52-4d13-b607-f2b585467e94.png)

Piercing vanilla enchantment as an example of what should be seen.
![2023-03-24_04 33 09](https://user-images.githubusercontent.com/90337398/227402010-a415e3ad-5102-4acc-b2c1-17fe6b539ed1.png)

**Versions (please complete the following information):**
 - Forge/Fabric Loader Version: Forge 43.2.8
 - MC Version: 1.19.2
 - Mod Version: VanillaTweaks-forge-1.19.2-1.5.65
 - JEI Version (if present) : jei-1.19.2-forge-11.6.0.1013
 - Fabric API Version (if present) :

**Additional context**
Other mods, at least most of them, don't have this problem.

**Comment by strikerrocker** [comment]
It seems to work fine with VanillaTweaks and JEI alone with the given version.
