### ISSUE TITLE
[BUG] No documentation.  What does this mod do?

### ISSUE THREAD

**Issue by allanonmage** [strikerrocker/VanillaTweaks#187]
**Describe the bug**
OK, so your mod shares the same name as the Hermitraft one.  But that's all I know.

**To Reproduce**
1. Go to the website.  Lack of reading material, so you can't progress.

**Expected behavior**
A clear and concise description of what the mod does.

**Screenshots**

**Versions (please complete the following information):**
 - Forge/Fabric Loader Version:
 - MC Version:
 - Mod Version:
 - JEI Version (if present) :
 - Fabric API Version (if present) :

**Log output/error (via. [Hastebin](http://hastebin.com/))**
Get your minecraft log and paste it in the above link and paste the link here.

**Additional context**

**Comment by strikerrocker** [comment]
You need javascript enabled for it to work
http://strikerrocker.github.io/vanillatweaks/
