### ISSUE TITLE
Auto replant bug 

### ISSUE THREAD

**Issue by SillyPuffin** [strikerrocker/VanillaTweaks#188]
It seems that mods which generate crops on non farmland blocks such as flax from supplementary spawning on sand can cause the game to crash. If the sand breaks/falls due to floating and then getting updated, at least in my case, the flax will break. because its a crop I guess auto replant then tries to replant however you cant plant crops in water or air so it crashes. 

after turning of the auto replant feature the game stopped crashing.

it doesn't seem to be repeatable with wheat if you set the block above a 1X1X2 sand tower with wheat and then break the sand
on the bottom even though it drops seeds. However if you repeat those steps with flax it breaks. I understand that flax is not your mod but if your mod can detect that its a crop and tries to replant it on the block below could it be fixed by making sure its farmland before replanting. I'm not sure if that would work because i don't really know minecraft code works but it kinda makes sense

Also i tried to use the black list feature for all the types of flax but it didn't seem to stop it. Is the blacklist for the tag of the seeds themselves or for the crop/plant that makes the seed when you break them?

crash report:
[crash-2023-04-22_19.40.08-server.txt](https://github.com/StrikerRockers-Mods/VanillaTweaks/files/11302181/crash-2023-04-22_19.40.08-server.txt)

example of how sand can fall in. This is the sand which caused my game to crash.
![2023-04-22_19 26 19](https://user-images.githubusercontent.com/89728058/233803632-5b6f4e8b-f212-4b18-974f-327604a4ea4c.png)

**Comment by strikerrocker** [comment]
Fixed the crashes for Minecraft 1.19.4 versions
