### ISSUE TITLE
[Crash] Flax seeds/plants causing ticking entity crash

### ISSUE THREAD

**Issue by Yakub-M** [strikerrocker/VanillaTweaks#189]
**Describe the bug**
This crash occurs happens anytime a player tries to place flax in the world or pick it up in dropped item form.

**Crash report**
https://hastebin.com/share/ufatorafic.yaml
https://hastebin.com/share/gocukocino.ruby

**To Reproduce**
1. Pick up flax seeds or render flax plant (Simply dropping flax seeds does not seem to cause the crash).
2. Done

**Versions:**
 - Fabric Loader Version:  0.14.19
 - MC Version: 1.19.2
 - Mod Version: 
 Supplementaries 2.3.4
 VanillaTweaks 1.5.65
 - Fabric API Version: 0.75.1

**Comment by Vinesauced** [comment]
Also happening to me in 1.19.2 on forge, happens both with flax seeds and amaranth seeds from Pam's harvest craft 2, and probably other seeds I haven't tested. I just threw a bunch of seeds on the grass block ground in a superflat world and it was enough to cause `ticking entity`. I also have supplementaries and various other mods installed.

I would like to thank the mod creator for adding the config option to disable this feature.

**Comment by MehVahdJukaar** [comment]
Actual fault reported here https://github.com/StrikerRockers-Mods/VanillaTweaks/issues/191

**Comment by strikerrocker** [comment]
Fixed the crashes for Minecraft 1.19.4 versions
