### ISSUE TITLE
you cant put signs on signs because of the edit feature which destroys a lot of farms

### ISSUE THREAD

**Issue by swedishmozart** [strikerrocker/VanillaTweaks#190]
**Type**
Item, Block, Tile Entity, Entity (Mob), Biome, Dimension, Other

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by strikerrocker** [comment]
Fixed the crashes for Minecraft 1.19.4 versions
