### ISSUE TITLE
[Crash] Self-plant Incompatibility with Enderscape mod

### ISSUE THREAD

**Issue by KB-Q** [strikerrocker/VanillaTweaks#192]
**Describe the bug**
Incompatibility with plant blocks in the enderscape mod.

**Crash report (via. [Hastebin](http://hastebin.com/))**
https://hastebin.com/share/ukocomelej.yaml

**To Reproduce**
The self plant feature in vanilla tweaks crashes the game when faced with plant blocks from the enderscape mod.

**Versions:**(check log if you don't know)
 - Forge/Fabric Loader Version: Fabric Loader 0.14.19
 - MC Version: 1.19.2
 - Mod Version: 1.5.65
 - JEI Version (if present) :
 - Fabric API Version (if present) :

**Additional context**

**Comment by strikerrocker** [comment]
Fixed the crashes for Minecraft 1.19.4 versions
