### ISSUE TITLE
[Crash] crash on launch

### ISSUE THREAD

**Issue by segev1708** [strikerrocker/VanillaTweaks#195]
**Describe the bug**
crash on launch, i dont no anything else

**Crash report (via. [Hastebin](http://hastebin.com/))**
https://hastebin.com/share/utidipaxot.yaml

 - Forge/Fabric Loader Version: 47.0.5
 - MC Version: 1.20.1
 - Mod Version: 1.20.1-1.5.68
 - JEI Version (if present) : jei-1.20.1-forge-15.2.0.22

**Comment by strikerrocker** [comment]
It seems like optifine is at fault here with forge not a fault of vanillatweaks
