### ISSUE TITLE
server/modpack

### ISSUE THREAD

**Issue by steve81398** [strikerrocker/VanillaTweaks#2]
my friend and i have been trying to use the modpack i have developed/put together on a server and every time we try to start the server it crashes or fails to start and cites vanilla tweaks as the issue

**Comment by strikerrocker** [comment]
Server log

**Comment by steve81398** [comment]
would you like to the server log?
or what do you mean i do not understand

**Comment by strikerrocker** [comment]
I want the server log to know the problem

**Comment by steve81398** [comment]
ok ill send it your way when my friend with the server gets it to me

**Comment by steve81398** [comment]
[crash-2017-10-28_00.54.26-server.txt](https://github.com/strikerrocker/VanillaTweaks/files/1424039/crash-2017-10-28_00.54.26-server.txt)

**Comment by strikerrocker** [comment]
I will look into it

**Comment by steve81398** [comment]
thank you much

**Comment by strikerrocker** [comment]
Has been fixed in the latest update

**Comment by steve81398** [comment]
thank you sir
