### ISSUE TITLE
Crash upon loading world

### ISSUE THREAD

**Issue by The-Fireplace** [strikerrocker/VanillaTweaks#20]
Before the crash, I logged into my world, and it was zoomed way in, despite me not having obtained binoculars. I exited and reloaded the save, and it was still zoomed in. Then, I restarted the game, and when I tried to load the world, it crashed.
Crash report:
https://paste.ubuntu.com/26509588/
VT 1.2.3
MC 1.12.2
Forge 14.23.1.2610

**Comment by strikerrocker** [comment]
Can you make sure that you dont have optifine if so please disable the dynamic fov optionand try again. If it crashes report it here

**Comment by The-Fireplace** [comment]
Ah, ok. When it was really zoomed in, I did have Optifine enabled, but I
disabled it when I restarted the game, and after Optifine was removed is
when the crash occured.
I'll test with Dynamic FOV disabled and see if that fixes it.

**Comment by The-Fireplace** [comment]
I've tested the same world again, without optifine, and again, it crashed. Looking at the crash report, it appears that not having Baubles loaded is what causes the crash. One sec, I'll make a PR that should fix this.

**Comment by The-Fireplace** [comment]
There, see #22
