### ISSUE TITLE
Crash upon harvesting carrot crop; Unexpected error

### ISSUE THREAD

**Issue by IRyanorI** [strikerrocker/VanillaTweaks#200]
**Describe the bug**
Bug occurred during 1.20.1 playthrough of latest version. I was by a village, trying to harvest a crop, I hit the crop once and the entire game crashed and closed me out immediately. It was a carrot crop that wasn't fully grown possibly. I found out that the error originated from the mod upon being told by the Fabric Discord community that this mod probably caused it.

**Crash Report**: https://hastebin.com/share/tibefujuxu.yaml

**To Reproduce**
1. Launch the game with puzzleslib, go in a world.
2. Maybe have a bunch of other mods installed. However, they did not say that they were involved, yet.
3. Find a crop (possibly ungrown in a village or other area), hit/harvest it with your character.
4. It crashed immediately.

**Versions:**(check log if you don't know)
 - Forge/Fabric Loader Version: _Fabric 0.15.1_
 - MC Version: _1.20.1_
 - Mod Version: VanillaTweaks _1.5.70_
 - JEI Version (if present): **Not Present**
 - Fabric API Version (if present): 0.91.0

**Additional context**
Not that I know of. The Fabric inspector said they were absolutely sure no other mods were involved, and that I should report the issue if it was the latest update causing it.

**Comment by goodguyham** [comment]
this happened to me aswell but with grass and potatoes too,

here's the crash report: https://pastebin.com/LZjeT8zV
