### ISSUE TITLE
[Crash] The latest version crashes the game with the mod AdventureZ

### ISSUE THREAD

**Issue by LeoDemitori** [strikerrocker/VanillaTweaks#201]
**Describe the bug**
The latest version crashes the game with the mod AdventureZ
p.s. 1.5.71 work normaly

**Crash report**
[vanillatweaks_adventureZ.txt](https://github.com/StrikerRockers-Mods/VanillaTweaks/files/13822700/vanillatweaks_adventureZ.txt)

**Versions:**(check log if you don't know)
 - Fabric Loader Version: 0.14.24
 - MC Version: 1.20.1
 - Mod Version: 1.5.72
 - Fabric API Version (if present) : 0.91.0

**Comment by strikerrocker** [comment]
Use VanillaTweaks-fabric-1.20.1-1.5.71. Version that you are using was mistakenly marked as supporting 1.20.1
