### ISSUE TITLE
[Crash] Crash when mining any block with the Blazing Enchantment.

### ISSUE THREAD

**Issue by Gbergz** [strikerrocker/VanillaTweaks#204]
**Describe the bug**
Game crashes when mining any block with the Blazing Enchantment.

**Crash report**
https://gist.githubusercontent.com/Gbergz/df6f45a406d2114d4e6e9f3ed2de9c3d/raw/8a37c280f7b34eb4a0e1d71a86b9f2d0c1cb775e/gistfile1.txt

**To Reproduce**
1. Get blazing enchantment on a shovel for example. (I used gold shovel).
2. Mine dirt.
3. Game freezes.
4. Game crashes.
game closed. crashed.

**Versions:**
 - Forge Version: 47.2.17
 - MC Version: 1.20.1
 - Mod Version: 1.5.72
 - JEI Version (if present) : 15.2.0.27

**Additional context**
None.

**Comment by strikerrocker** [comment]
You are using the version meant for 1.20.2. Use this file https://www.curseforge.com/minecraft/mc-mods/vanillatweaks/files/5004559

**Comment by Gbergz** [comment]
Gotcha. Well, I updated the mod through CurseForge app, didnt do anything special to achieve that version.
