### ISSUE TITLE
Crash using VT and Dynamic Surrondings

### ISSUE THREAD

**Issue by vpontin** [strikerrocker/VanillaTweaks#24]
Random crash while walking on the map...

crash-log: https://gist.github.com/vpontin/8c3e0621ef01ca6b1e153d6ebca0c75e

Using MC 1.12.2, Forge 14.23.2.2613, VanillaTweaks 1.2.5 and DynamicSurrondings 3.4.9.2

Also reported on DS side, https://github.com/OreCruncher/DynamicSurroundings/issues/238

**Comment by strikerrocker** [comment]
It is something to do with dynamic surroundings

**Comment by vpontin** [comment]
Ok. Waiting @OreCruncher reply on DS issue

**Comment by OreCruncher** [comment]
Actually it looks like the self planting capability provider is responding that my emoji capability belongs to it.  If the provider returns non-null it means it supports the capability, which in this case it obviously does not.
