### ISSUE TITLE
Issues using VT and a fork of Timberjack

### ISSUE THREAD

**Issue by vpontin** [strikerrocker/VanillaTweaks#26]
Hi!
I use [this fork](https://github.com/asiekierka/Timberjack/commit/ea2f7a7c82594afd9e3628fb37dee9dab225809c) of Timberjack mod ([original by CoverJaguar](https://github.com/asiekierka/Timberjack) - [Curse](https://minecraft.curseforge.com/projects/timberjack)) made by @asiekierka , but when i've installed VanillaTweaks the tree felling behaviour stopped working.
Plus i dont get any errors in logs. Can this issue be fixed?

**Comment by strikerrocker** [comment]
No idea what is wrong .Maybe @asiekierka can help.

**Comment by vpontin** [comment]
Sorry, forgot to say that.
As i said in OP, VanillaTweaks is neutralizing the Timberjack feature - the tree felling physics. Without VT timberjack works fine.

**Comment by strikerrocker** [comment]
@vpontin can you explain what doesnt. Whether the trees doesnt fall? Or there is no drops?

**Comment by vpontin** [comment]
The trees dont fall
