### ISSUE TITLE
Config option to disable rotten flesh to leather recipe

### ISSUE THREAD

**Issue by DWX12** [strikerrocker/VanillaTweaks#28]
Would like a config option added to disable the rotten flesh to leather recipe for those who don't want to have to resort to using craft tweaker to remove it. It would be useful as a game balancing option.

**Comment by strikerrocker** [comment]
Closed in [d308e2d](https://github.com/strikerrocker/VanillaTweaks/commit/e1c0384ae570bc2bd4f720aa83b10e0b41887078)

**Comment by strikerrocker** [comment]
@DWX12  Will upload the updatedd version soon
