### ISSUE TITLE
X-Ray issue when pedestal is placed

### ISSUE THREAD

**Issue by DWX12** [strikerrocker/VanillaTweaks#29]
Whatever block the pedestal gets placed on becomes transparent from the top.

![2018-03-14_14 07 47](https://user-images.githubusercontent.com/37384543/37431016-39269ec8-2791-11e8-8707-c3acef613f59.png)
![2018-03-14_14 08 18](https://user-images.githubusercontent.com/37384543/37431017-3947c7c4-2791-11e8-9224-c24589cab9c0.png)

**Comment by strikerrocker** [comment]
This doesn't occur when blocks placed at sides?

**Comment by DWX12** [comment]
Don't believe so, I'll have to double check. So far it's only the block directly below it.

**Comment by strikerrocker** [comment]
Closed in [d308e2d](https://github.com/strikerrocker/VanillaTweaks/commit/e1c0384ae570bc2bd4f720aa83b10e0b41887078)
