### ISSUE TITLE
Crash when run game

### ISSUE THREAD

**Issue by matyklugDebbuged** [strikerrocker/VanillaTweaks#3]
https://pastebin.com/5uNBBkBe

it this mod require any core?

**Comment by strikerrocker** [comment]
Nope I think I have figured the issue out I will push a update

**Comment by strikerrocker** [comment]
Can you tell me what version it affects??

**Comment by matyklugDebbuged** [comment]
minecraft:1.12.2 mod:1.1.5

**Comment by strikerrocker** [comment]
Possibly solved this in
https://github.com/strikerrocker/VanillaTweaks/commit/0864eac36d7f57d59e98110b90666d2ccd19bee3
