### ISSUE TITLE
Nametags drop

### ISSUE THREAD

**Issue by Fortist** [strikerrocker/VanillaTweaks#30]
After narrowing it down to this mod, name tags drop every time you kill something with a name

So, it causes issues with mods like V-Tweaks that name mobs every once in a while.

**Comment by strikerrocker** [comment]
Thanks for reporting this. I will definitely add a config option in drops category for mod compatibility. Also i will tinker around the idea of only dropping nametags when only killed by a player. So it doesnt allow easy access for nametags.

**Comment by strikerrocker** [comment]
Closed in [d308e2d](https://github.com/strikerrocker/VanillaTweaks/commit/e1c0384ae570bc2bd4f720aa83b10e0b41887078)
