### ISSUE TITLE
But why...?

### ISSUE THREAD

**Issue by Dalethium** [strikerrocker/VanillaTweaks#35]
https://github.com/strikerrocker/VanillaTweaks/blob/0be367097f2d275a0d4e2401880db6b38fe05ab6/src/main/java/io/github/strikerrocker/vt/events/BlockEvents.java#L52

Why does this need to be printed haha

**Comment by KaptainWutax** [comment]
LOL, I think it was just for testing. xD *Remove your prints Striker!*

**Comment by strikerrocker** [comment]
As kaptain said that's the reason. I will remove it in the next update. Thanks for reporting
