### ISSUE TITLE
Slime Chunk Finder config error

### ISSUE THREAD

**Issue by DWX12** [strikerrocker/VanillaTweaks#37]
**Vanilla Tweaks Version**:

 1.3.2

**MinecraftForge Version**:

 NA

**Minecraft Version**:

 1.12.2

**(Optional) Just Enough Items (JEI) Version**:

 

**Client or Server?**:
- [ X ] Client
- [ ] Server

**Crash Report (via. [Pastebin](http://pastebin.com/))**:

 NA

**What happens / happened?**:

 Under the "Recipes" section in the config file there's an error with the syntax and possibly no way to enable/disable the slime chunk finder:

recipes {
    # Is rotten flesh to leathEnables the Slime Chunk Finderer recipe enabled?
    B:leather=false

**How can I reproduce it?**:

 Should be able to just start up Minecraft with just Vanilla Tweaks to get the config file and take a look at it from there.

**(Optional) Mod List**:

**Comment by strikerrocker** [comment]
Copy pasta errored thanks will fix this asap
