### ISSUE TITLE
Quality Tools Mod can't apply qualitites to Totem of Undying due to them being stackable. (Issue: Config option for changing stack sizes for various items)

### ISSUE THREAD

**Issue by TripleTomTv** [strikerrocker/VanillaTweaks#38]
**Vanilla Tweaks Version**:

 VanillaTweaks-1.3.2

**MinecraftForge Version**:

  1.12.2-forge1.12.2-14.23.4.2703

**Minecraft Version**:

 1.12.2

**(Optional) Just Enough Items (JEI) Version**:

jei_1.12.2-4.9.1.191

**Client or Server?**:
- [X] Client
- [X] Server

**Crash Report (via. [Pastebin](http://pastebin.com/))**:

 No Crash

**What happens / happened?**:

 The config for changing stack sizes for various items (Which includes the Totem of Undying) only allows a minimum stack size of 3 and this conflicts with the Quality Tools mod, which adds random qualities with random attribute bonuses for tools, armors and baubles. (Like in Terraria)
The Mod requires the items to be unstackable so it can apply a random Quality but since there's no way to reduce the stack size to just 1, the Totem of Undying can't get qualities even if you only take 1 from the creative inventory or get them regularly, even without stacking them. They can never get qualities. I tested it with the Totem Expansion Mod too, which adds several new totems and they can get qualities because they can't be stacked. I was also using the BaublesOfUndying Mod (Ability to put Totem in Baubles Slot), but Quality Tools doesn't require it to apply qualitites to the Totem of Undying.

**How can I reproduce it?**:

 Just take 1 Totem of Undying from the creative inventory or get one regularly with both VanillaTweaks and Quality Tools mods installed.

**(Optional) Mod List**:
VanillaTweaks-1.3.2
PotionCore-1.6_for_1.12.2 (Required for Quality Tools)
QualityTools-1.0.6_for_1.12.2
totemexpansion-1.2.0-1.12.2
Baubles-1.12-1.5.2
BaubleOfUndying-1.12-1.0.1

**Solution**:

 Add a config, so we can enable/disable the changeable stack sizes for various items option, or set the minimum to 1.

Hopefully my post isn't too confusing and i also hope that this rather small issue can be fixed with not too much work needed. I'll be very thankful and really appreciate it, if you can fix this! :)

**Comment by strikerrocker** [comment]
Maybe an separate category for the stack changes or something else. I will look into it anyways.
