### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by jprocket45** [strikerrocker/VanillaTweaks#41]
**Vanilla Tweaks Version**:  1.4

**MinecraftForge Version**:  14.23.5.2768

**Minecraft Version**: 1.12.2

**(Optional) Just Enough Items (JEI) Version**: 1.12.2-4.13.1.220

**(Optional) Baubles Version**: 

**Client or Server?**:
- [ ] Client
- [X] Server

**Crash Report (via. [Hastebin](http://hastebin.com/))**:     https://pastebin.com/GTXBNbz8

**What happens / happened?**:   server crashes before loading up all the way

**How can the issue be reproduced?**: I think just by addming VT to the server side and loading server.

** Mod List**:   https://pastebin.com/QdhTEMaX

was using hastbin till it said something went wrong error posted via pastebin for now.

**Comment by strikerrocker** [comment]
Can you send me the server log?

**Comment by jprocket45** [comment]
[latest.log](https://github.com/strikerrocker/VanillaTweaks/files/2545202/latest.log)

**Comment by jprocket45** [comment]
hopefully thats what you needed let me know if there is anything else or if this is even your issue lol

**Comment by strikerrocker** [comment]
It is. Tho it would take me a while to fix this as i am not near my computer anytime soon so i would suggest you use an older version

**Comment by jprocket45** [comment]
sorry for the late response ill wait not in a really big hurry :)

**Comment by strikerrocker** [comment]
Fixed this issue and pushed an update to curseforge but it may take a while to review and upload the file by the team
