### ISSUE TITLE
Crash on Startup 1.42

### ISSUE THREAD

**Issue by Lordbaane** [strikerrocker/VanillaTweaks#43]
**Vanilla Tweaks Version**:
1.42
**MinecraftForge Version**:
5.2772
**Minecraft Version**:
1.12.2
**(Optional) Just Enough Items (JEI) Version**:
3.237
**(Optional) Baubles Version**: 
1.52
**Client or Server?**:
- [x ] Client
- [ ] Server

https://paste.dimdev.org/gebefeboja.mccrash

**What happens / happened?**:
Crash During Startup
**How can the issue be reproduced?**:

** Mod List**:
See Pastebin

**Comment by strikerrocker** [comment]
Fixed in 1.4.3 and pushed an update
