### ISSUE TITLE
Mr. Striker, items in the crafting pad don't feel so good.

### ISSUE THREAD

**Issue by MisterShawn** [strikerrocker/VanillaTweaks#49]
**Vanilla Tweaks Version**:
1.4.7
**MinecraftForge Version**:
14.23.5.2825
**Minecraft Version**:
1.12.2
**(Optional) Just Enough Items (JEI) Version**:
4.15.0.275
**(Optional) Baubles Version**: 

**Client or Server?**:
- [X] Client
- [?] Server

**Crash Report (via. [Hastebin](http://hastebin.com/))**:
N/A
**What happens / happened?**:
When closing the GUI of the crafting pad any items left in will be deleted.
**How can the issue be reproduced?**:
Open crafting pad, put items in, close GUI, reopen GUI. 
** Mod List**:
I'll post my mod list if you can't reproduce this bug.

**Comment by strikerrocker** [comment]
Nor do i feel so good mr.sdaddy. I dont have access to my PC for half a week but i will look into it as soon as i can

**Comment by strikerrocker** [comment]
Hmm i can't seem to reproduce this bug. If you can post the mod list i will reopen then issue again.

**Comment by Erdi2609** [comment]
I am playing the Life in the village modpack and I have the same issue

**Comment by strikerrocker** [comment]
@Erdi2608 can you tell me the version of VanillaTweaks you are using and if its old can you update it?

**Comment by IChris2698I** [comment]
I am also playing Life in the Village, and I also have this issue. The version listed in my mod list is `Vanilla Tweaks 1.12.2-1.5.4`

Sounds like it might be a cross-mod conflict, since you can't reproduce it locally.

**Comment by strikerrocker** [comment]
Can you create a new issue? I can't fix it in this week due to exams thus it would serve as a reminder.

**Comment by IChris2698I** [comment]
Sure, but I'll see if I can narrow it down a bit first.

**Comment by IChris2698I** [comment]
For anybody finding this issue in the future, the new issue is #66. It was a conflict with RealBench, and affected other hand-held crafting tables too.
