### ISSUE TITLE
Version 1.1.9 crashes on launch.

### ISSUE THREAD

**Issue by TeetoKaziim** [strikerrocker/VanillaTweaks#5]
Minecraft: 1.12.2
Forge: 14.23.1.2556
VanillaTweaks: 1.1.9

When I try to launch the client, I get this crash:

Crash Report: https://pastebin.com/raw/BASwkfWr

Thought maybe it was an incompatibility, but stripped an instance down to just vt, and forge, and still getting the same thing. 1.1.8 seems to work just fine, for me.

Thanks for your time and consideration, and best of luck. Lovin the mod.

**Comment by strikerrocker** [comment]
Can I get the log . Thanks for the nice words

**Comment by TeetoKaziim** [comment]
fml-client-latest.log? 

https://pastebin.com/raw/sixdpmSs

**Comment by strikerrocker** [comment]
Did you enable the debug option in twitch/curse launcher try disabling it and run the game

**Comment by mvdhoning** [comment]
i am having the same error on launch.
i have been looking in curse launcher, but i cannot find an debug option there.

**Comment by mvdhoning** [comment]
what strikes me as odd is this:
~[vt$RegsitrationHandler.class:?]
possibly an typo ;-)
also that class might not exist as you define that class inside vt.java
you might consider moving it to its own java file so it gets an .class file on compiling it.

**Comment by TeetoKaziim** [comment]
Sorry for the delay. I'm looking around in the Twitch App Settings and not finding a "Debug Setting", what sub section would it be in?

**Comment by strikerrocker** [comment]
Closes with[f85f72d](https://github.com/strikerrocker/VanillaTweaks/commit/f85f72d3dc2e8c7e9be0393586b1d25558850a12)

**Comment by strikerrocker** [comment]
Will be available on CurseForge once approved
