### ISSUE TITLE
no config sync on stone recipes

### ISSUE THREAD

**Issue by BadKaiPanda** [strikerrocker/VanillaTweaks#50]
**Vanilla Tweaks Version**:
    VanillaTweaks-1.4.7.jar

**MinecraftForge Version**:
    forge-14.23.5.2824

**Minecraft Version**:
    1.12.2

**(Optional) Just Enough Items (JEI) Version**:

**(Optional) Baubles Version**: 
    	jei_1.12.2-4.15.0.268.jar

**Client or Server?**:
- [*] Client
- [*] Server

**Crash Report (via. [Hastebin](http://hastebin.com/))**:
None

**What happens / happened?**:
    The client and server are not syncing the client is still added the stone recipe even when the server as it disabled.

**How can the issue be reproduced?**:
    Install it on the server and client set stone to false

**Mod List**:
    N/A in this case, tested it on it's own

**Comment by strikerrocker** [comment]
Hmm have you actually used the recipe or are you seeing it on jei?

**Comment by BadKaiPanda** [comment]
We are seeing it still I haven't used it as most times when you use something what's not on a server you get kicked but since JEI is used for all recipes it's kinds needed, but the problem is it's not syncing from the server what is kinda is needed for a tweaking mod unless we can run this on the server only and for go it been on the client but I never seen forge mods work like that :)

**Comment by strikerrocker** [comment]
Rewrote the entire mod can you test it and reopen if the issue still exists?

**Comment by BadKaiPanda** [comment]
I will rest this soon as I can.
