### ISSUE TITLE
Crash on startup new VN tweaks update

### ISSUE THREAD

**Issue by JesterMcMuffin** [strikerrocker/VanillaTweaks#51]
**Vanilla Tweaks Version:**
VanillaTweaks-1.4.7.jar (2019/05/11)

**MinecraftForge Version:**
forge-14.23.5.2824

**Minecraft Version:**
1.12.2

**(Optional) Just Enough Items (JEI) Version:**

**(Optional) Baubles Version:**
jei_1.12.2-4.15.0.268.jar

**Crash Report **
https://paste.dimdev.org/xaxomisefu.mccrash

**What happens / happened?:**
The New update you released seems to crash it on launch. Possibly conflicting with iron chests?

**Mod List:**
Included in crash report

**Comment by strikerrocker** [comment]
Hey thanks for reporting the issue. I know what's causing the issue and can't fix it until tomorrow so use vanilla tweaks 1.4.6 for now

**Comment by strikerrocker** [comment]
Hey i cant seem to reproduce the issue. If you can join my [discord](https://discord.gg/tqcqeSj) i can send you a custom version you can test available in #minecraft-mods channel?

**Comment by strikerrocker** [comment]
Iron Chests have fixed the issue but not released a new version yet thus i will close the issue when it is released and issue is confirmed fixed.

**Comment by strikerrocker** [comment]
Fixed in new build. Reference commit : https://github.com/StrikerRockers-Mods/VanillaTweaks/commit/ea7399d7dbc10f149afb6306900920b693f6bc51
