### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by Pseudohuman93** [strikerrocker/VanillaTweaks#52]
Hello,
There seems to be an issue between this mod and the ZAWA mod

- https://paste.dimdev.org/jupupifubu.mccrash

**Comment by strikerrocker** [comment]
Fixed in new build. Reference commit : https://github.com/StrikerRockers-Mods/VanillaTweaks/commit/ea7399d7dbc10f149afb6306900920b693f6bc51
