### ISSUE TITLE
Idea / Suggestion 

### ISSUE THREAD

**Issue by Arctic90x** [strikerrocker/VanillaTweaks#56]
Add a locking function to all blocks using a lock and key for a server and(or) multiplayer use. Make it so once the item is locked it becomes unusable to all other players and make locked items unbreakable.

Also, have a way to rename your locks and keys using the anvil, and maybe include a Key Ring(s) that can hold 8 keys by putting the key ring into the middle of the crafting table with the 8 keys around it. 

I'd have a Master Key that can be used as 8 keys by putting 8 keys into the Crafting Table and have it useable with 8 locks by putting the key in the middle of the crafting table with the 8 locks around it, and maybe have an Admin Key that can be used to open any locked items, and besides that only have the locked items usable again is have the locks removable in Creative mode or be broken by any admin.

**Comment by strikerrocker** [comment]
Adding a lock and key seems out of scope of the mod. It would be better to add locking mechanism of some sort to pedestal alone. Can you modify the issue accordingly?
