### ISSUE TITLE
Not fully working with JEI

### ISSUE THREAD

**Issue by Arctic90x** [strikerrocker/VanillaTweaks#57]
**Vanilla Tweaks Version**:  1.5.2

**MinecraftForge Version**: 14.23.5.28.38

**Minecraft Version**: 1.12.2

**(Optional) Just Enough Items (JEI) Version**: 4.15.0.281

**Client or Server?**:
- [x] Client
- [ ] Server

**What happens / happened?**: Items show up in Just Enough Items (JEI) even if disable them, and items don't show recipes

**How can the issue be reproduced?**: I'm not sure if you can or if it's JEI that need to fix this

**Suggestion 1** Maybe also change it so if you disable a crafting recipe it also disables the item altogether and removes it from set tab it's in and can't generate within the world?

**Suggestion 2** Have in the config file a to modify the min or max level for enchanting

**Comment by strikerrocker** [comment]
It is intended that the items show up in JEI as removing registry things is not recommended by forge thus config only disable the recipe. Min/max level for enchantments for config would cause some enchantments to malfunction thus i am not implementing it.
