### ISSUE TITLE
Server enchanting

### ISSUE THREAD

**Issue by PhantomBeast987** [strikerrocker/VanillaTweaks#60]
**Vanilla Tweaks Version**:1.12.2

**MinecraftForge Version**:12.23.5.2838

**Minecraft Version**:1.12.2

**(Optional) Just Enough Items (JEI) Version**:4.12.0.268

**(Optional) Baubles Version**: 1.5.2

**Client or Server?**:
- [ ] Client
- [X ] Server

**Crash Report (via. [Hastebin](http://hastebin.com/))**:

**What happens / happened?**:When I try to apply the vanilla tweaks enchants like "Vigor", "Nimble", and "Hops" (Only 3 ive found so far) it doesnt work. It acts like it will but when I pick it up it vanishes and the book and armor goes back into the anvil slots.

**How can the issue be reproduced?**:Start up a server and try to apply one of the enchants

** Mod List**:**"Roguelike Adventures and Dungeons" from Twitch modpack launcher**
AtomicStryker's Infernal Mobs (by AtomicStryker)
Waystones (by BlayTheNinth)
IvToolkit (by Ivorforce)
Quality Tools (by Tmtravlr)
The Disenchanter Mod (by eusunt)
Random Loot Mod (by milomaz1)
DimensionalDoors (by DimensionalDevelopment)
Reliquary v1.3 (by P3pp3rF1y)
Open Terrain Generator (OTG) (by team_otg)
Scaling Health (by SilentChaos512)
NetherEx (by LogicTechCorp)
No Recipe Book (by Seneschal_Luwin)
Placeable Items (by Ferdz)
VanillaTweaks (by StrikerRocker)
Bountiful (by ejektaflex)
Dungeon Tactics (by PegBeard)
Tropicraft (by Cojomax99)
ItemPhysic Lite (by CreativeMD)
V-Tweaks (by oitsjustjose)
VanillaFix (by Runemoro)
Improved Backpacks (by DreenDex)
AutoRegLib (by Vazkii_)
CraftTweaker (by Jaredlll08)
BiblioCraft (by JDSinclair)
Progressive Bosses (by InsaneGames_)
Controlling (by Jaredlll08)
stimmedcow : NoMoreRecipeConflict (by Oliv1er)
Enchantment Descriptions (by Darkhax)
Extra Spells (Electroblob's Wizardry) (by meldexun)
ForgeEndertech (by EnderLanky)
Cyclic (by Lothrazar)
Heroic Armory (by skeddles)
Aether: Lost Content (by KingPhygieBoo)
Creeper Confetti (by SR2610)
Biome Bundle (by mc_pitman)
Mowzie's Mobs (by BobMowzie)
Notes (by ChaosTheDude)
FTB Utilities (by FTB)
Iron Backpacks (by gr8pefish)
Just Enough Items (JEI) (by mezz)
Living Enchantment (by Clownvin)
Tomb Many Graves 2 (by M4thG33k)
Land Manager (by bright_spark)
Baubles (by azanor)
Aroma1997Core (by Aroma1997)
Rough Tweaks (by Lellson)
Rustic (by mangoose3039)
FoamFix for Minecraft (by asiekierka)
FTB Library (by FTB)
Akashic Tome (by Vazkii_)
Skewers (by casadis)
Inventory Pets (by Purplicious_Cow)
Nature's Compass (by ChaosTheDude)
Simple Storage Network (by Lothrazar)
Roguelike Dungeons (by Greymerk)
Cyclops Core (by kroeser)
TombManyGraves 2 API (by M4thG33k)
CplPibald's Tweaks (by CplPibald)
TombManyPlugins - Cosmetic Armor Reworked (by M4thG33k)
Neat (by Vazkii_)
Signpost (by Gollorum)
Terracart Reloaded (by kreezxil)
Just Enough Resources (JER) (by Way2muchnoise)
Shadowfacts' Forgelin (by shadowfactsmc)
Potion Core (by Tmtravlr)
Aether Continuation (by Raptor4694)
Extra Alchemy (by zabi94)
Portable Crafting (by gr8pefish)
LimeLib (by KidsDontPlay)
Cosmetic Armor Reworked (by ZLainSama)
Sound Filters (by Tmtravlr)
Doomlike Dungeons (by BlackJar72)
Charm (by svenhjol)
MegaLoot (by Winter_Grave)
Chest Transporter (by CubeX2)
Pyramid Plunder (by Laton95)
Spice of Life: Carrot Edition (by LordCazsius)
Silent Lib (by SilentChaos512)
Random Things (by lumien231)
OreLib (by OreCruncher)
The Aether (by GildedGames)
ConnectedTexturesMod (by tterrag1098)
Jack-O'-Launcher (by ochotonida)
Enhanced Armaments (by jannesoon)
AI Improvements (by DarkGuardsman)
Bloodmoon (by lumien231)
Ore Excavation (by Funwayguy)
Chisel (by tterrag1098)
LibraryEx (by LogicTechCorp)
Quark (by Vazkii_)
Doggy Talents (by percivalalb)
Totemic (by ljfa)
SwingThroughGrass (by exidex)
Spawn Temple (by iastre)
Custom Main Menu (by lumien231)
Chance Cubes (by turkey2349)
Rats (by alex1the1666)
DefaultSettings (by PT400C)
Cavern II (by _kegare)
EZStorage 2 (by zero__fall)
Prefab (by WuestMan)
Inventory Tweaks (by Kobata)
AppleSkin (by squeek502)
Resource Loader (by lumien231)
Bigger Packets Please (by ElNounch65668)
Aquaculture (by Shadowclaimer)
Better Questing - Quest Book (by Drethic)
Unique Crops (by bafomdad)
Subterranean Switcheroo (by ArloTheEpic)
Recurrent Complex (by Ivorforce)
Engineers Workshop Reborn (by modmuss50)
Nomadic Tents (by skyjay1)
Fast Leaf Decay (by Olafskii)
Ordinary Coins (by flametaichou)
World Primer (by masa_)
Mouse Tweaks (by YaLTeR97)
The Twilight Forest (by Benimatic)
Aroma1997s Dimensional World (by Aroma1997)
BetterFps (by Guichaguri)
Mystical Agriculture (by BlakeBr0)
Cucumber Library (by BlakeBr0)
LLibrary (by iLexiconn)
Electroblob's Wizardry (by electroblob)
Customized Dungeon Loot (by XxRexRaptorxX)
Login Shield (by Glasspelican)
Level Up! Reloaded (by BeetoGuy)
Better Questing (by Funwayguy)
Better Questing - Standard Expansion (by Funwayguy)
Project: Vibrant Journeys (by solis_nova123)
OpenModsLib (by OpenMods)
OpenBlocks (by OpenMods)
Straw Golem (by fradige9512794)
Dynamic Surroundings (by OreCruncher)
[ANGRY PIXEL] The Betweenlands (by oily_oli)
JourneyMap (by techbrew)
Hwyla (by TehNut)
GottschCore (by gottsch)
Phosphor (by jellysquid_)
FTB Utilities: Backups (by LatvianModder)
Extra Utilities (by RWTema)
Comforts (by theillusivec4)
ViesCraft - Airships! (by Viesis_Gaming)
The Beneath (by Shinoow)
Colossal Chests (by kroeser)
AppleCore (by squeek502)
The Eight Fabled Blades (by shelterrin)
Better Advancements (by Way2muchnoise)
InGame Info XML (by Lunatrius)
LunatriusCore (by Lunatrius)
Reborn Core (by modmuss50)

**Comment by strikerrocker** [comment]
There exists no  VanillaTweaks verson as 1.12 .2 can you provide the correct version (can be seen under VanillaTweaks in mods)

**Comment by strikerrocker** [comment]
Also if you are using RAD i would recommend you update the VanillaTweaks version alone as yesterday i released an version which fixed server crash related to enchantments.

**Comment by SvRDM** [comment]
This is also happening to me, only on a server, in version 1.5.3 of Vanilla Tweaks. Though I've only seen it with nimble (haven't tested the others).

**Comment by strikerrocker** [comment]
Update to 1.5.4 version of vanillatweaks
