### ISSUE TITLE
VanillaTweaks 1.5.4 still crashing servers even when it's the only mod loaded

### ISSUE THREAD

**Issue by tiniestkid** [strikerrocker/VanillaTweaks#61]
**Vanilla Tweaks Version**: 1.5.4

**MinecraftForge Version**: 14.23.5.2768

**Minecraft Version**: 1.12.2

**Just Enough Items (JEI) Version**: 4.15.0.268 

**Baubles Version**: 1.5.2

**Client or Server?**:
- [ ] Client
- [x] Server

**Crash Report (via. [Pastebin](http://pastebin.com/))**: https://pastebin.com/R79Fth6j (hastebin still down, sorry) 

**What happens / happened?**: I installed the new update but the issue with VanillaTweaks crashing servers is still coming up. This time I included the full server log from boot to crash. If that's too much information, I also posted just the crash log's contents here: https://pastebin.com/p9iZPCz8

**How can the issue be reproduced?**: Loading the mod into a forge 12.2 server still gives the same issue. Here's a GitHub repository of the files I used to test the server: https://github.com/tiniestkid/test-server

JEI & Baubles are included in the test files.

**Mod List**:
- VanillaTweaks
- Just Enough Items
- Baubles

Sorry about all the trouble. I know you're working hard during your free time to fix these bugs and I really appreciate your work. Thanks.

**Comment by strikerrocker** [comment]
Could you provide the log file?
Never mind

**Comment by tiniestkid** [comment]
> 
> 
> Could you provide the log file?

Sorry, just realized I forgot to post the repository link. 

Here's the repo: https://github.com/tiniestkid/test-server

Here's the logs folder: https://github.com/tiniestkid/test-server/tree/master/logs

**Comment by strikerrocker** [comment]
Thanks

**Comment by strikerrocker** [comment]
Do you wear a helmet with veteran on the server?

**Comment by strikerrocker** [comment]
Also can you join my discord i will give you a custom build to try

**Comment by tiniestkid** [comment]
I haven't tried using the enchantment in-server yet. Also, sure I can join discord.

**Comment by strikerrocker** [comment]
The issue was using the recommended forge version instead of latest.
