### ISSUE TITLE
this happened thought i would submit this

### ISSUE THREAD

**Issue by owl3child** [strikerrocker/VanillaTweaks#62]
**Vanilla Tweaks Version**:1.4.8

**MinecraftForge Version**:forge-14.23.5.2831

**Minecraft Version**:1.12.2

**(Optional) Just Enough Items (JEI) Version**:

**(Optional) Baubles Version**: 

**Client or Server?**:
- [x] Client
- [ ] Server

**Crash Report (via. [Hastebin](http://hastebin.com/): https://paste.dimdev.org/obusiguvun.mccrash

**What happens / happened?**: I got a notification that this mod could corrupt my game but it didn't cause a crash

**How can the issue be reproduced?**: not sure

** Mod List**
Name                     Author                                   File

Advanced Rocketry  	zmaster587	 AdvancedRocketry-1.12.2-1.6.0-162-universal.jar	

AI Improvements	  DarkGuardsman	  AIImprovements-1.12-0.0.1b3.jar	

Akashic Tome  	Vazkii_	AkashicTome-1.2-12.jar	

AppleCore	  squeek502	AppleCore-mc1.12.2-3.2.0.jar	

AppleSkin	  squeek502	AppleSkin-mc1.12-1.0.9.jar	

Aquaculture	  Shadowclaimer	Aquaculture-1.12.2-1.6.8.jar	

AutoRegLib	     Vazkii        _	AutoRegLib-1.3-30.jar	

Bailey's Dailies 	ToroCraft	              dailies-1.12.2-6.jar	

Baubles            	Azanor13                	Baubles-1.12-1.5.2.jar	

Better Advancements	  way2muchnoise	   BetterAdvancements-1.12.2-0.1.0.77.jar	

Better Builder's Wands   	Portablejim	BetterBuildersWands-1.12.2-0.13.2.271+5997513.jar	

Better Questing       	Funwayguy	      BetterQuesting-3.5.299.jar	

Better Questing - Quest Book	      Drethic	        questbook-3.1.1-1.12.jar	

Better Questing - Standard Expansion	  Funwayguy	   StandardExpansion-3.4.159.jar	

Better With Lib (BWM - Core)	      primetoxinz	     BetterWithLib-1.12-1.5.jar	

Better With Mods	     primetoxinz	     BetterWithMods-1.12-2.3.20-1027.jar	

BetterFps	                    Guichaguri                  	BetterFps-1.4.8.jar	

BiblioCraft	 JDSinclair           	BiblioCraft[v2.4.5][MC1.12.2].jar	

Biome Bundle        	mc_pitman	       Biome_Bundle-1.12.2-v6.1.jar	

Bountiful                	ejektaflex                       	Bountiful-2.2.0.jar	

Buildcraft	                 CovertJaguar                      	buildcraft-all-7.99.24.1.jar	

Chameleon            	jaquadro	                          Chameleon-1.12-4.1.3.jar	

Chance Cubes         	turkey2349       	ChanceCubes-1.12.2-4.0.0.271.jar	

Charm	                 svenhjol             	Charm-1.12.2-1.1.12.jar	

Chest Transporter       	CubeX2                 	ChestTransporter-1.12.2-2.8.8.jar	

Chisel                 	tterrag1098                             	Chisel-MC1.12.2-0.2.1.35.jar	

Colossal Chests              	kroeser	         ColossalChests-1.12.2-1.7.3.jar	

Comforts             	theillusivec4	            comforts-1.12.2-1.4.1.2.jar	

Compressed Items          	cesar_zorak             	Compressed Items-1.4.jar	

ConnectedTexturesMod       	tterrag1098	       CTM-MC1.12.2-0.3.3.22.jar	

Controlling	            Jaredlll08       	Controlling-3.0.6.jar	

Cooking for Blockheads    	BlayTheNinth	          CookingForBlockheads_1.12.2-6.4.70.jar	

Corail Tombstone	                   Corail_31	                              tombstone-3.5.5-1.12.jar	

CoralReef           	primetoxinz	                               CoralReef-2.5-1.12.2.jar	

Cosmetic Armor Reworked	  ZLainSama	   CosmeticArmorReworked-1.12.2-v4a.jar	

CplPibald's Tweaks             	CplPibald          	PiTweaks-1.12-1.1.1.jar	

CraftTweaker	                 Jaredlll08	                    CraftTweaker2-1.12-4.1.19.jar	

Creeper Confetti	       SR2610	                 creeperconfetti-1.4.2.jar	

Cucumber Library	          BlakeBr0           	Cucumber-1.12.2-1.1.3.jar	
 
Custom Main                 Menu	lumien231          	CustomMainMenu-MC1.12.2-2.0.9.jar	

Cyclops Core             	kroeser	             CyclopsCore-1.12.2-1.3.0.jar	
  
Doggy Talents    	percivalalb          	DoggyTalents-1.12.2-1.15.0.2-universal.jar	

Dungeon Tactics         	PegBeard          	DungeonTactics-1.12.2-0.16.5.jar	

Electroblob's Wizardry	  electroblob      	Electroblob's Wizardry - 4.1.4 - MC 1.12.2.jar	

Extra Alchemy                  	zabi94	                   extraalchemy-0.3.8.6.1-release.jar	

Fairy Lights	                    pau101	                fairylights-2.1.7-1.12.2.jar	

Familiar Fauna                       	GlitchfiendMods              	FamiliarFauna-1.12.2-1.0.11.jar	

Farseek	              delvr                          	Farseek-1.12-2.3.2.jar	

FastWorkbench	         Shadows_of_Fire	           FastWorkbench-1.12.2-1.7.2.jar	

FoamFix for Minecraft           	asiekierka           	foamfix-0.10.5-1.12.2.jar	

FTB Library              	FTB                	FTBLib-5.4.3.117.jar	

FTB Utilities                  	FTB              	FTBUtilities-5.4.0.97.jar	

FTB Utilities: Backups	              LatvianModder	         FTBUtilitiesBackups-1.0.0.4.jar	

Future MC	             thedarkcolour	                  future-mc-0.1.5c.jar	

Garden Stuff	            jaquadro	               GardenStuff-1.12-2.1.1.jar	

Hwyla                      	TehNut             	Hwyla-1.8.26-B41_1.12.2.jar	

Improved Hoes	               Furgl	                  ImprovedHoes-1.12-1.2.2.jar	

InGame Info XML	          Lunatrius	             InGameInfoXML-1.12.2-2.8.2.94-universal.jar	

Inspirations                 	KnightMiner           	Inspirations-1.12.2-0.2.4.jar	

Inventory Tweaks	                    Kobata	              InventoryTweaks-1.63.jar	

Iron Backpacks	               gr8pefish               	IronBackpacks-1.12.2-3.0.8-12.jar	

Iron Chests	               progwml6	      ironchest-1.12.2-7.0.72.847.jar	

ItemPhysic Lite           	CreativeMD           	ItemPhysic Lite 1.3.7 mc1.12.2.jar	

JourneyMap	          techbrew            	journeymap-1.12.2-5.5.4.jar	

Just Enough Items (JEI)	            mezz            	jei_1.12.2-4.15.0.268.jar	

Just Enough Resources (JER)        	way2muchnoise      	JustEnoughResources-1.12.2-0.9.2.58.jar	

Landlust - Furniture	               streifentier	           landlust-1.12.2-0.3.6.jar	

Level Up! Reloaded	                BeetoGuy                  	Level Up! 2-1.1.22-1.12.jar	

LibraryEx                	LogicTechCorp	       LibEx-1.12.2-1.0.8.jar	

LibVulpes         	zmaster587            	LibVulpes-1.12.2-0.4.1-60-universal.jar	

Living Enchantment	                  Clownvin              	living_enchantment-3.1.9.jar	

LLibrary	              iLexiconn	                 llibrary-1.7.19-1.12.2.jar	

Login Shield	           Glasspelican            	Login_Shield-1.12.2-3-g7c6e7ac.jar	

LunatriusCore	            Lunatrius	               LunatriusCore-1.12.2-1.2.0.42-universal.jar	

Mantle                        	mDiyo                     	Mantle-1.12-1.3.3.55.jar	

MegaLoot                	Winter_Grave	                    megaloot-1.12.2-0.2.30.jar	

Millénaire           	Kinniken                         	millenaire-1.12.2-7.2.1.jar	

Minecolonies	             H3lay	         minecolonies-1.12.2-0.10.259-RELEASE-universal.jar	

ModTweaker	               Jaredlll08                   	modtweaker-4.0.17.jar	

Mouse Tweaks         	YaLTeR97	                    MouseTweaks-2.10-mc1.12.2.jar	

MTLib	                         Jaredlll08                                 	MTLib-3.0.6.jar	

Mystic World	            EpicSquid319                    	MysticWorld-1.12.2-1.3.2.jar	

MysticalLib                  	EpicSquid319              	mysticallib-1.12.2-1.3.1.jar	

NetherEx	                        LogicTechCorp	                    NetherEx-1.12.2-2.0.8.jar	

No Mob Spawning on Trees	        oldjunyi          	NoMobSpawningOnTrees-1.2.2-mc1.12.2.jar	

No Recipe Book	           Seneschal_Luwin	            noRecipeBook_v1.2.2formc1.12.2.jar	

Notes	            ChaosTheDude                  	Notes-1.12-1.1.1.jar	

Open Terrain Generator (OTG)	 team_otg	OpenTerrainGenerator-1.12.2 - v6.jar	

OpenBlocks Elevator            	VsnGamer             	ElevatorMod-1.12.2-1.3.11.jar	

Ore Excavation	              Funwayguy	        OreExcavation-1.4.140.jar	

OreLib	               OreCruncher	                OreLib-1.12.2-3.5.2.2.jar	

Paintings ++         	senpaisubaraki	                morepaintings-paintings-1.12.2-5.0.1.1.jar	

Pam's HarvestCraft        	MatrexsVigil        	Pam's HarvestCraft 1.12.2zd Surprise for Yogcast.jar	

Patchouli	             Vazkii_        	Patchouli-1.0-20.jar	

Pickle Tweaks	          BlakeBr0	              PickleTweaks-1.12.2-2.1.3.jar	

Ping         	Girafi     	Ping-1.12.2-1.4.5.jar	

PinklySheep Mod	        The_Wabbit0101         	pinklysheep-mc1.12.2-4.0.jar	

Placebo	           Shadows_of_Fire	           Placebo-1.12.2-1.6.0.jar	

Potion Core	            Tmtravlr            	PotionCore-1.6_for_1.12.2.jar	

Prefab	           WuestMan	                 prefab-1.3.0.26.jar	

Project: Vibrant Journeys	            solis_nova123	    ProjectVibrantJourneys-1.12.2-1.6.3.jar	

Quality Tools	            Tmtravlr              	QualityTools-1.0.6_for_1.12.2.jar	

Quark               	Vazkii            _	Quark-r1.5-160.jar	

RandomPatches       	TheRandomLabs          	randompatches-1.12.2-1.16.1.0.jar	

Rats                    	alex1the1666            	rats-1.1.1.jar	

RealBench                	Prototik              	RealBench-1.12.2-1.3.3.jar	

ReAuth	          TechnicianLP          	reauth-3.6.0.jar	

Repurpose              	WuestMan              	Repurpose-1.0.0.19.jar	

Resource Loader	                   lumien231             	ResourceLoader-MC1.12.1-1.5.3.jar	

Roguelike Dungeons	    Greymerk            	RoguelikeDungeons-1.12.2-1.8.0.jar	

Roots	                    EpicSquid319                    	Roots-1.12.2-3.0.4.jar	

Rope Bridge	                         LordCazsius	                        ropebridge-1.12-2.0.7.jar	

Rustic                       	mangoose3039	                   rustic-1.1.0.jar	

Shadowfacts' Forgelin	       shadowfactsmc                      	Forgelin-1.8.3.jar	

Signpost                 	Gollorum                	signpost-1.12-1.06.1.jar	

Simply Tea!	                     EpicSquid319	           simplytea-1.6.jar	

Sound Filters                            	Tmtravlr              	SoundFilters-0.10_for_1.12.jar	

Spice of Life: Carrot Edition	                     LordCazsius               	solcarrot-1.12.2-1.7.jar	

StepUp	                 NotTooManyItems	           StepUp-1.0.2-mc1.10-1.12.jar	

stimmedcow : NoMoreRecipeConflict           	Oliv1er	     NoMoreRecipeConflict-0.13(1.12.2).jar	

Storage Drawers	             jaquadro            	StorageDrawers-1.12.2-5.3.8.jar	

Streams                       	delvr           	Streams-1.12-0.4.7.jar	

Terracart Reloaded               	kreezxil                 	terracartreloaded-1.12.2-1.2.3.jar	

The Flying Things                    	Corail_31              	flying_things-1.5.2-1.12.jar	

Tinkers Construct                  	mDiyo	                  TConstruct-1.12.2-2.12.0.157.jar	

Tomb Many Graves 2                        	M4thG33k	          TombManyGraves-1.12-4.2.0.jar	

TombManyGraves 2 API	           M4thG33k	      tombmanygraves2api-1.12.2-1.0.0.jar	

TombManyPlugins - Cosmetic Armor Reworked	         M4thG33k	tombmanypluginscosmeticarmorreworked-1.0.0.jar	

Totemic          	ljfa              	Totemic-1.12.2-0.11.6.jar	

Tree Chopper            	DuchLord           	TreeChopper-1.12.2-1.2.4.jar	

Unique Crops	          bafomdad	 uniquecrops-1.12-0.1.76.jar	

V-Tweaks    	oitsjustjose	       VTweaks-1.12.2-2.0.2.jar	

VanillaFix          	Runemoro      	VanillaFix-1.0.10-99.jar	

VanillaFoodPantry Mod	          The_Wabbit0101	        vanillafoodpantry-mc1.12.2-4.3.1.jar	

VanillaTweaks            	StrikerRocker	          VanillaTweaks-1.4.8.jar	

VeinMiner	Portablejim        	VeinMiner-1.12-0.38.2.647+b31535a.jar	

ViesCraft - Airships!    	Viesis_Gaming          	ViesCraft-1.12.2-5.9.13.jar	

Waila Harvestability     	squeek502           	WailaHarvestability-mc1.12-1.1.12.jar	

Wawla - What Are We Looking At	        DarkhaxDev            	Wawla-1.12.2-2.5.273.jar	

Waystones	        BlayTheNinth	            Waystones_1.12.2-4.0.67.jar	

World Primer	         masa_	           worldprimer-1.12.2-0.5.0.jar	

Yoyos

**Comment by strikerrocker** [comment]
You are using an old version of vanillatweaks. I would recommend you update to the latest version 1.5.4
