### ISSUE TITLE
Items are lost when left in the crafting grid

### ISSUE THREAD

**Issue by DarkYuan** [strikerrocker/VanillaTweaks#63]
**Vanilla Tweaks Version**:
1.4.8
**MinecraftForge Version**:
14.23.5.2831
**Minecraft Version**:
1.12.2
**(Optional) Just Enough Items (JEI) Version**:
4.15.0.268
**(Optional) Baubles Version**: 
1.12-1.5.2
**Client or Server?**:
- [x] Client
- [x] Server

**Crash Report (via. Hastebin)**:
N/A
**What happens / happened?**:
Items are lost when leaving the crafting pad GUI
**How can the issue be reproduced?**:
Download Life in the Village modpack (version 1.12 - current as of Aug. 15, 2019). Using the crafting pad and leaving anything inside it, either an uncrafted result, or just items.
**What should happen?**:
The crafting pad doesn't seem to use a normal crafting GUI. For instance, JEI doesn't get dimmed, and items don't have tooltips. In a normal crafting window, these features are present, as well as any items left behind get dropped in front of you.
**Mod List**:
[Life in the Village modpack (version 1.12)](https://www.curseforge.com/minecraft/modpacks/life-in-the-village/relations/dependencies)

Hopefully the addition of a modlist should help the issue be reproduced.

**Comment by strikerrocker** [comment]
Update to latest version of the mod.

**Comment by susnux** [comment]
This is still an issue!
With the latest version (1.5.5) for minecraft 1.12, the craftingpad still loose items left in the pad when exiting the gui.

**Comment by strikerrocker** [comment]
Its an compatibility issue with a mod called real bench that i cant fix.
