### ISSUE TITLE
Remove blocks and advancemnets that are disabled in config

### ISSUE THREAD

**Issue by EternalOne11** [strikerrocker/VanillaTweaks#64]
Can you add an option in the configs to remove the blocks/items that are disabled in the configs in the game. Also, it would be apricated if you also added the option to disable the advancements as well. Both of these features would be much appreciated.

**Comment by strikerrocker** [comment]
Forge doesn't endorse registering things by config that's why i only disable the recipe.

**Comment by EternalOne11** [comment]
hm, then how do other mods do it then. quark for example.

**Comment by strikerrocker** [comment]
By endorse i mean doesn't appreciate doing it.

**Comment by EternalOne11** [comment]
ok
