### ISSUE TITLE
Game hangs / crash on creating a new world (MC 1.14.4)

### ISSUE THREAD

**Issue by MatthiasMann** [strikerrocker/VanillaTweaks#67]
**Vanilla Tweaks Version**: 1.5.5

**MinecraftForge Version**: 28.1.1

**Minecraft Version**: 1.14.4

**(Optional) Just Enough Items (JEI) Version**: 6.0.0.11

**(Optional) Baubles Version**: not installed

**Client or Server?**: Single player

**Crash Report (via. [Hastebin](http://hastebin.com/))**:
[crash-2019-09-16_19.55.37-server.txt](https://github.com/StrikerRockers-Mods/VanillaTweaks/files/3617546/crash-2019-09-16_19.55.37-server.txt)

**What happens / happened?**:
Game hangs / crash on creating a new world

**How can the issue be reproduced?**:
Yes

** Mod List**: In the crash report

**Comment by strikerrocker** [comment]
Hey thanks for reporting the issue. I tested on server but not production i will release a fix tomorrow.
