### ISSUE TITLE
[1.14.4] Crash Report, WritingException at startup

### ISSUE THREAD

**Issue by Wynadorn** [strikerrocker/VanillaTweaks#68]
**Describe the bug** (Required)
The Server crashes on start-up, I've deleted the world before starting.

**To Reproduce** (Required unless not known)
1. Create a new server with the listed .jar's
2. Start the server

**Crash report (via. [Hastebin](http://hastebin.com/))**
https://hastebin.com/raw/vahovicuko

**Expected behavior** (Required)
Not to crash 😅

**Versions:**(check log if you don't know)
 - Forge Version: forge-1.14.4-28.1.1.jar
 - MC Version: minecraft_server.1.14.4.jar
 - Mod Version: VanillaTweaks-1.14.4.1.5.6.jar
 - JEI Version (if present) : jei-1.14.4-6.0.0.12.jar
 - Baubles Version (if present) :

**Additional context**
Add any other context about the problem here. This may be skipped/removed.

**Comment by strikerrocker** [comment]
Hey can you show vanillatweaks config folder?

**Comment by Wynadorn** [comment]
![image](https://user-images.githubusercontent.com/4095127/65060563-67a9e080-d978-11e9-9b4b-401ed8960fd2.png)

**Comment by strikerrocker** [comment]
Delete the content.toml folder and try again please.

**Comment by Wynadorn** [comment]
I've made an empty file called Content.toml and now it works

> Delete the content.toml folder and try again please.

Will do

**Comment by Wynadorn** [comment]
Yeah, now everything's fine, I suppose a previous version could have caused issues.

Thanks for the quick reply, and fix!

**Comment by strikerrocker** [comment]
Could you trying using the latest version of the mod in an new instance?
