### ISSUE TITLE
preditor/prey relationships do not work? (mod compat with animania?)

### ISSUE THREAD

**Issue by mvdhoning** [strikerrocker/VanillaTweaks#7]
More realistic predator/prey relationships! When ocelots kill chickens, the chickens won't drop meat! Same for wolves and sheep!
Does not seem to work for me but that might be due to animania sheep.
https://minecraft.curseforge.com/projects/animania
Also there does not seem to be a config option for this.

**Comment by strikerrocker** [comment]
Thanks for reporting this

**Comment by strikerrocker** [comment]
As animania doesn't have a source an compat couldnt be made. I will add a config for this

**Comment by strikerrocker** [comment]
https://github.com/strikerrocker/VanillaTweaks/commit/e096378d783245baab9790fb53f84c429c92809d
