### ISSUE TITLE
Disabling Better Stone Tools Removes Vanilla Stone Tool Recipes

### ISSUE THREAD

**Issue by MarioAndWeegee3** [strikerrocker/VanillaTweaks#77]
**Describe the bug** (Required)
After setting the `betterStoneTools` option to `false`, the vanilla recipes are not added instead of the new recipes.

**To Reproduce** (Required unless not known)
1. In the `vanillatweaks\Crafting.toml` file, change `betterStoneTools` to `false`
2. In-game, the Vanilla recipes for the stone tools will not work.

**Log output/error (via. [Pastebin](https://pastebin.com/hzjdnGaj))**

**Expected behavior** (Required)
Stone tools should use the default, vanilla recipes.

**Screenshots**
![2019-11-01_14 30 07](https://user-images.githubusercontent.com/35458805/68047190-22393c80-fcb4-11e9-8e62-5f15cd9536a2.png)

**Versions:**(check log if you don't know)
 - Forge Version: 28.1.76
 - MC Version: 1.14.4
 - Mod Version: 4.1.5.10
 - JEI Version (if present) : 6.0.0.18

**Comment by strikerrocker** [comment]
Hmm better stone tools and better recipe for stone stairs doesn't work at all. I am sure this is due to some other mod.
