### ISSUE TITLE
Suggestion: being able to sit on 'half-bed' blocks

### ISSUE THREAD

**Issue by sepsol** [strikerrocker/VanillaTweaks#78]
**Type**
Other

**Module**
Tweaks. 

**Is your feature request related to a problem? Please describe.**
There are some cool looking throne-like chairs that you can build using `half-bed` blocks and it frustrates me that I can't sit on them!

**Describe the solution you'd like**
I want to be able to sit on `half-bed` blocks other than `stairs` and `slabs`.

**Describe alternatives you've considered**
Maybe having an invisible tool or block (like `barriers`) that you can use or put on top of any block to make them sittable?!

**Additional context**
Sitting blocks are obtained by one of these ways:
- by running the command: `/setblock ~ ~ ~ minecraft:red_bed`
- using a `debug stick` on a `bed`

![2019-11-12_15 37 06](https://user-images.githubusercontent.com/47871887/68670687-bd5acd80-0562-11ea-9a57-4a87d0eb9098.png)

(The sitting of the chair is a half-bed block)

**Comment by strikerrocker** [comment]
Hey thanks for the suggestion but i don't think it fits in the mod as its survival mode compatible.

**Comment by sepsol** [comment]
It could still make a cool looking sit-able admin throne though! :)
