### ISSUE TITLE
Allow the Display Pedestal to be Waterlogged

### ISSUE THREAD

**Issue by WenXin20** [strikerrocker/VanillaTweaks#79]
**Type**
Block

**Module**
Content for 1.14.4

**Is your feature request related to a problem? Please describe.**
Currently, display stands can't be waterlogged.

**Describe the solution you'd like**
Allowing it to be waterloggable could allow for underwater display of items

**Describe alternatives you've considered**
N/A

**Comment by strikerrocker** [comment]
Implemented in [4ef3592](https://github.com/StrikerRockers-Mods/VanillaTweaks/commit/c6e5571ca0da50b3729b547d151547102ed5e93d)
