### ISSUE TITLE
Understanding how Nimble enchantment works

### ISSUE THREAD

**Issue by Andremani** [strikerrocker/VanillaTweaks#81]
Am i correctly understand that following string means Nimble I gives player +20% to total speed (including other speed bonuses) and Nimble III gives +60%?
If not, can you tell me please how it exactly works?

`AttributeModifier speedModifier = new AttributeModifier(nimbleUUID, "Nimble", (float) enchantmentLevel * 0.20000000298023224, AttributeModifier.Operation.MULTIPLY_TOTAL);`

**Comment by strikerrocker** [comment]
Yes what you are saying is current.
