### ISSUE TITLE
incompatibility issue  with minecolonies

### ISSUE THREAD

**Issue by Lazersgm** [strikerrocker/VanillaTweaks#84]
**Describe the bug** (Required)
if you use the shears to remove a minecolonies citizens name you can not rename them after.
**To Reproduce** (Required unless not known)
1. use shears to remove the name of a minecolonies citizens name
2. use a name tag on the minecolonies citizen by shift right clicking them.

**Log output/error (via. [Hastebin](http://hastebin.com/))**
Get your minecraft log and paste it in the above link and paste the link here.

**Expected behavior** (Required)
what should happen is they have the new name. what happens is they use up the tag and nothing happens.
**Screenshots**
If applicable, add screenshots to help explain your problem. This may be skipped/removed.

**Versions:**(check log if you don't know)
 - Forge Version: 
1.12.2-14.23.5.2838
 - MC Version:
1.22.2
 - Mod Version:
1.12.2-1.5.6
 - JEI Version (if present) :
1.12.2-4.15.0.291
 - Baubles Version (if present) :
1.12-1.5.2

**Additional context**
Add any other context about the problem here. This may be skipped/removed.
talked to the mine colonies devs and they said to send you a report on this.

**Comment by strikerrocker** [comment]
Hey sorry for the late reply. I am not supporting 1.12 version of the mod anymore.
