### ISSUE TITLE
Uncapped Enchantments not working [1.14]

### ISSUE THREAD

**Issue by groovysmooth** [strikerrocker/VanillaTweaks#85]
[1.14] Using version 1.14.4.1.5.12 , I was not able to raise any of the vanilla enchantments above their predetermined values. I have replicated this with 0 additional mods. 

Example: Combining two Sharpness V books in an anvil results in another Sharpness V (It takes around 5xp and allows you to take the finished product, as if it thinks its producing a Sharpness VI)

(Same results when combining 2 books, 1 book / 1 sword, and 2 swords. Recreated with various other vanilla enchantments like efficiency and protection on different pieces of gear.)

I also see no options in the config regarding this feature, which I think would be a great addition to customization/troubleshooting.

Would love this feature to work, as I can't find any other mods that do the same for 1.14

Really forward to seeing this fixed, take care!

**Comment by strikerrocker** [comment]
Hey I think you misunderstood a feature. By default vanilla only shows the
translation for 12 levels of potion or enchantment. This feature only
increases the support for the translation of potion or enchantment and
doesnt increase the level you can obtain in vanilla.
