### ISSUE TITLE
Additional Falling Blocks dont fall?

### ISSUE THREAD

**Issue by mvdhoning** [strikerrocker/VanillaTweaks#9]
Looking in vt.cfg i see an additional falling blocks option, in it are dirt and clay.
Yet dirt and clay behave like dirt and clay would and not as sand as the description of the config options suggests.

On the other hand i am not sure if i would like dirt behaving like sand so when the feature works i think i may remove clay and dirt from that config option.

forge: 14,23.0.2544
vt: 1.1.10
minecraft 1.12
other mods: yes

**Comment by strikerrocker** [comment]
The feature is never going to be implemented as it doesn't sound great. I have left it unknowingly. It will be removed in the next update.

**Comment by mvdhoning** [comment]
ok i leave this open as a reminder for you to remove the feature from the config.

**Comment by strikerrocker** [comment]
Removed in the latest update. remove the older config and retry
