### ISSUE TITLE
[1.15.2] Homing Crossbows

### ISSUE THREAD

**Issue by Dragnier** [strikerrocker/VanillaTweaks#91]
**Type**
Other

**Module**
Enchanting

**Is your feature request related to a problem? Please describe.**
Yes, technically... Homing doesn't recognize Crossbows; vanilla or modded.

**Describe the solution you'd like**
Homing should also work with the Crossbow.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by strikerrocker** [comment]
Crossbows are different from bows thus they have different enchantments in vanilla. So I am not adding this.
