### ISSUE TITLE
Mob Spawners Are Pigs

### ISSUE THREAD

**Issue by Duxtorm** [strikerrocker/VanillaTweaks#92]
**Describe the bug** (Required)
When I mine a spawner, it turns into a pig spawner as soon as I place it.

**To Reproduce** (Required unless not known)
1. o.o; Break spawner with silk touch diamond pick.... 
2. Place spawner :v 

**Log output/error (via. [Hastebin](http://hastebin.com/))**
Get your minecraft log and paste it in the above link and paste the link here.
https://hastebin.com/asudedigip.sql

**Expected behavior** (Required)
I placed a "spider" spawner and thought a spider spawner was gonna be placed

**Screenshots**
https://i.imgur.com/X9ZTG3W.png
https://i.imgur.com/eUvMSjY.png

**Versions:**(check log if you don't know)
 - Forge Version: 31.1.18
 - MC Version: 1.15.2
 - Mod Version: 1.5.18
 - JEI Version (if present) : 6.0.0.2
 - Baubles Version (if present) :
 - Curios Version (if present) :

**Comment by etbourreau** [comment]
I can confirm with precisions:
On private server hosted on my computer, I never had this issue (around 5~6 spawners mined) but my friend just mined one and got a pig spawner

**Comment by strikerrocker** [comment]
Hey @etbourreau can you provide the mod list. This seems to be a compatability issue with some mod. The mod list could help narrow it down

**Comment by etbourreau** [comment]
Sure, we are currently using:
- AmbientSounds 3.0.16
- FallingTree 2.0.3+19
- Xaero's Minimap 20.5.0
(and others but they wasn't installed when this issue appened)

**Comment by Duxtorm** [comment]
Hm.. I also have Ambient sounds
;w; don't tell me I gotta get rid of ambient sounds
