### ISSUE TITLE
Pedestals cannot be crafted

### ISSUE THREAD

**Issue by etbourreau** [strikerrocker/VanillaTweaks#94]
**Describe the bug** (Required)
Pedestals are available in creative mode but cannot be crafted (nor present in easy craft panel)

**To Reproduce** (Required unless not known)
1. go in survival mode
2. try to craft a pedestal as:
```
SSS
ABA
SBS
```
(where S = stone brick slab, B = stone brick block and A = air)

**Log output/error (via. [Hastebin](http://hastebin.com/))**
no error

**Expected behavior** (Required)
Pedestal should be craftable

**Versions:**(check log if you don't know)
 - Forge Version: 31.1.18
 - MC Version: 1.15.2
 - Mod Version: 1.5.18

**Comment by strikerrocker** [comment]
Fixed
