### ISSUE TITLE
Placing items in pedestals

### ISSUE THREAD

**Issue by etbourreau** [strikerrocker/VanillaTweaks#96]
**Describe the bug** (Required)
When placing item in pedestal while not having items in secondary hands, item swith to secondary hands first, then to pedestal with another right click

**To Reproduce** (Required unless not known)
1. set yourself in survival mode
2. empty your secondary hand
3. get item to place on the pedestal in your main hand
4. right click

**Log output/error (via. [Hastebin](http://hastebin.com/))**
no error

**Expected behavior** (Required)
maybe the pedestal should only be affected by the main hand ?

**Screenshots**
https://clips.twitch.tv/InexpensiveBovineLouseVoteNay

**Versions:**(check log if you don't know)
 - Forge Version: 31.1.18
 - MC Version: 1.15.2
 - Mod Version: 1.5.18

**Comment by strikerrocker** [comment]
I don't understand?

**Comment by strikerrocker** [comment]
Never mind figured it out.
