### ISSUE TITLE
Placing multiple items in pedestal

### ISSUE THREAD

**Issue by etbourreau** [strikerrocker/VanillaTweaks#97]
**Describe the bug** (Required)
When you have multiple item your hand and right clicking the pedestal, all items are placed

**To Reproduce** (Required unless not known)
1. set yourself in survival mode
2. get multiple items in your hand
3. right click

**Log output/error (via. [Hastebin](http://hastebin.com/))**
no error

**Expected behavior** (Required)
maybe the pedestal should only take one item ?

**Screenshots**

**Versions:**(check log if you don't know)
 - Forge Version: 31.1.18
 - MC Version: 1.15.2
 - Mod Version: 1.5.18

**Comment by strikerrocker** [comment]
Pedestal being able to hold a stack of same time type of item is intended.
